import React from "react";
import styled from "@emotion/styled";
import Image from "next/image";
/**
 * `<AppbarParentSite>` ('appbar-parent-site')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=19:1937)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=19:1937)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <AppbarParentSite/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1f5abd8c-95d5-4bd8-a931-e935de073cf7)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/19:1937 -->
 */
export function AppbarParentSite() {
  return (
    <RootWrapperAppbarParentSite href="https://grida.co" target="_blank">
      <Home>
        <Logo64>
          <Image src="/grida-logo-white-128.png" width={25} height={25} />
        </Logo64>
        <Grida>Grida</Grida>
      </Home>
    </RootWrapperAppbarParentSite>
  );
}

const RootWrapperAppbarParentSite = styled.a`
  cursor: pointer;
  background-color: black;
  position: relative;
  height: 50px;
`;

const Home = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 8px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + -484px)) - 37px));
  top: 12px;
  width: 73px;
  height: 26px;
`;

const Logo64 = styled.div`
  width: 25px;
  height: 26px;
  overflow: hidden;
  position: relative;
`;

const LogoShapeOnly = styled.div`
  width: 25px;
  height: 25px;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Union = styled.img`
  width: 25px;
  height: 25px;
  object-fit: cover;
  position: absolute;
  left: 0px;
  top: 0px;
`;

const Grida = styled.span`
  color: white;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Helvetica, sans-serif;
  font-weight: 700;
  letter-spacing: -1px;
  text-align: left;
`;
