import React from "react";
import styled from "@emotion/styled";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
/**
 * `<Appbar>` ('appbar')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=18:1889)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=18:1889)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Appbar/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d8000780-f44d-4ccf-b5da-f132856fc5aa)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/18:1889 -->
 */
export function Appbar() {
  const router = useRouter();
  const onGetStartedClick = () => {
    router.push("/get-started");
  };

  return (
    <RootWrapperAppbar>
      <ContentFrame>
        <Leading>
          <Home>
            <Image src={"/logo.svg"} height={20} width={100} />
          </Home>
          <Menus>
            {/* <MenuItem label="Docs" href="/docs" /> */}
            <MenuItem label="Playground" href="/playground" />
            {/* <MenuItem label="Pricing" href="#pricing" /> */}
            <MenuItem
              label="Github"
              href="https://github.com/gridaco/cors.sh"
            />
          </Menus>
        </Leading>
        <HeaderCtaSignupPlain>
          <HeaderCtaSignupPlain_0001>
            <GetStarted onClick={onGetStartedClick}>Get started</GetStarted>
          </HeaderCtaSignupPlain_0001>
        </HeaderCtaSignupPlain>
      </ContentFrame>
    </RootWrapperAppbar>
  );
}

const MenuItem = ({ label, href }: { label: string; href: string }) => {
  return (
    <MenuContainer href={href}>
      <BaseHeaderPrimaryMenu>
        {/* <MenuMargin /> */}
        <MenuTextContainer>
          <MenuText>{label}</MenuText>
        </MenuTextContainer>
        {/* <Indicator /> */}
      </BaseHeaderPrimaryMenu>
    </MenuContainer>
  );
};

const RootWrapperAppbar = styled.header`
  background-color: white;
  position: relative;
  z-index: 9;
  height: 80px;
`;

const ContentFrame = styled.div`
  width: 1040px;
  overflow: hidden;
  position: absolute;
  left: calc((calc((50% + 0px)) - 520px));
  top: 0px;
  bottom: 0px;
`;

const Leading = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 120px;
  box-sizing: border-box;
  position: absolute;
  left: 0px;
  top: calc((calc((50% + 0px)) - 30px));
  width: 732px;
  height: 60px;
`;

const Home = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  flex: none;
  gap: 8px;
  box-sizing: border-box;
`;

const Menus = styled.nav`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  flex: none;
  gap: 36px;
  height: 60px;
  box-sizing: border-box;
`;

const MenuContainer = styled(Link)`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  flex: none;
  box-sizing: border-box;
`;

const BaseHeaderPrimaryMenu = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  flex: none;
  gap: 16px;
  box-sizing: border-box;
`;

const MenuMargin = styled.div`
  height: 2px;
  background-color: white;
  align-self: stretch;
  flex-shrink: 0;
  opacity: 0;
`;

const MenuTextContainer = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  flex: none;
  box-sizing: border-box;
  cursor: pointer;
`;

const MenuText = styled.span`
  color: rgb(139, 139, 139);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 500;
  text-align: left;
`;

const HeaderCtaSignupPlain = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  position: absolute;
  top: calc((calc((50% + 0px)) - 16px));
  right: 0px;
  min-width: 80px;
  height: 32px;
`;

const HeaderCtaSignupPlain_0001 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  gap: 10px;
  border-radius: 35px;
  box-sizing: border-box;
`;

const GetStarted = styled.span`
  cursor: pointer;
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Roboto, sans-serif;
  font-weight: 500;
  text-align: right;
`;
