# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

service: cors-proxy
useDotenv: true
custom:
  customDomain:
    domainName: proxy.cors.sh
    basePath: ""
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: false
    # enabled only for production - configured by package.json script with --domain flag.
    enabled: ${param:domain, false}

  serverless-offline:
    httpPort: 4020
    lambdaPort: 3020
    noPrependStageInUrl: true

provider:
  name: aws
  memorySize: 128
  runtime: nodejs14.x
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - "*/*"
    endpointType: regional
  region: us-west-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    RATE_LIMIT_REDIS_URL: ${env:RATE_LIMIT_REDIS_URL}
    RATE_LIMIT_REDIS_USERNAME: ${env:RATE_LIMIT_REDIS_USERNAME}
    RATE_LIMIT_REDIS_PASSWORD: ${env:RATE_LIMIT_REDIS_PASSWORD}
    API_KEY_TEMP_AES_KEY: ${env:API_KEY_TEMP_AES_KEY}
    API_KEY_TEMP_AES_IV: ${env:API_KEY_TEMP_AES_IV}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    # for auth, managed by service.cors.sh
    DYNAMODB_TABLE_SERVICE_KEYS: "cors-proxy-service-keys-${opt:stage, self:provider.stage}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        # this service only needs to read the service keys
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_SERVICE_KEYS}"

# The `functions` block defines what code to deploy
functions:
  api:
    handler: src/index.handler
    maximumEventAge: 60
    maximumRetryAttempts: 0
    timeout: 12
    events:
      - http:
          path: /{proxy+}
          method: any
          # authorizer:
          #   name: cors-proxy-authorizer
          #   identitySource: "method.request.header.x-cors-api-key"
          #   type: token
          #   resultTtlInSeconds: 3600 # 1 hour
          #   arn: ${env:CORS_PROXY_AUTHORIZER_ARN}
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager
