import React from "react";
import styled from "@emotion/styled";
/**
 * `<CorsSh>` ('cors.sh')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=1:892)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=1:892)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <CorsSh/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/fd42b885-e04d-4d8f-86b8-4f262314099b)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/1:892 -->
 */
export function CorsSh() {
  return (
    <RootWrapperCorsSh>
      <Frame580>
        <Frame575>
          <Frame574 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3a9fb784-9b97-41ac-a4ea-aa07ab6e83f2" alt="icon"/>
        </Frame575>
        <FetchImagesFromInstagram>
          Fetch images from instagram
        </FetchImagesFromInstagram>
      </Frame580>
      <Frame577>
        <SickOfCorsErrors>
          Sick of<br/>
cors errors?
        </SickOfCorsErrors>
        <AFastReliableCorsProxyForYourWebsites>
          A Fast & Reliable CORS Proxy for your websites
        </AFastReliableCorsProxyForYourWebsites>
      </Frame577>
      <SimpleUsage>
        Simple usage
      </SimpleUsage>
      <YouCanUseTheProxyServiceBySimplyAddingHttpsCorsShToYourExistingApi>
        You can use the proxy service by simply adding https://cors.sh/ to your existing api
      </YouCanUseTheProxyServiceBySimplyAddingHttpsCorsShToYourExistingApi>
      <Pricing>
        Pricing
      </Pricing>
      <Frame560/>
      <Frame579>
        <Image2 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3bad2a57-b704-4e3d-aec6-4fd3e2b207d0" alt="image of Image2"/>
      </Frame579>
      <Frame4>
        <GetHttpsCorshShHttpsInstragramComPosts123HApiKeyGetYourApiKey>
          GET https://corsh.sh/ https://instragram.com/posts/123<br/>
-h api-key get-your-api-key
        </GetHttpsCorshShHttpsInstragramComPosts123HApiKeyGetYourApiKey>
        <CUrl>
          cURL
        </CUrl>
        <Js>
          JS
        </Js>
        <Sdk>
          SDK
        </Sdk>
        <ViewAllExamples>
          View all examples
        </ViewAllExamples>
      </Frame4>
      <Frame555>
        <Frame549>
          <HttpsExampleCom>
            https://example.com
          </HttpsExampleCom>
        </Frame549>
        <Frame550>
          <Frame551>
            <Frame556>
              <Get>
                GET
              </Get>
            </Frame556>
            <Frame30>
              <Line6/>
              <IconsMdiArrowDropDown src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7aeb0b00-0583-4eab-ac1f-51f362222c82" />
            </Frame30>
          </Frame551>
        </Frame550>
      </Frame555>
      <Frame570>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/49d2b9f3-55f0-45bb-ac55-e67e8beff73c" alt="icon"/>
          <Secure>
            Secure
          </Secure>
        </Frame562>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/836360f7-6088-4809-8f96-ed6cf8e69efc" alt="icon"/>
          <Reliable>
            Reliable
          </Reliable>
        </Frame562>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/acec4cdd-4360-478d-b2a2-8cf0b71a4aea" alt="icon"/>
          <Fast>
            Fast
          </Fast>
        </Frame562>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/23646d63-7630-4399-89d3-8fc2ef611c39" alt="icon"/>
          <ACorsAnywhereMirror>
            A cors-anywhere mirror
          </ACorsAnywhereMirror>
        </Frame562>
      </Frame570>
      <Frame566>
        <Frame565>
          <Home>
            <Logo64>
              <LogoShapeOnly>
                <Union src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3e8af193-56e2-447e-9679-a9075628012c" alt="image of Union"/>
              </LogoShapeOnly>
            </Logo64>
            <GridaAppServices>
              Grida App Services
            </GridaAppServices>
          </Home>
        </Frame565>
        <Appbar>
          <Frame33>
            <Leading>
              <Home_0001>
                <CorsSh_0001>
                  CORS.SH
                </CorsSh_0001>
              </Home_0001>
              <Menus>
                <BaseHeaderPrimaryMenu>
                  <BaseHeaderPrimaryMenu_0001>
                    <Rectangle784/>
                    <Frame281>
                      <Menu>
                        Docs
                      </Menu>
                    </Frame281>
                    <Indicator/>
                  </BaseHeaderPrimaryMenu_0001>
                </BaseHeaderPrimaryMenu>
                <BaseHeaderPrimaryMenu>
                  <BaseHeaderPrimaryMenu_0001>
                    <Rectangle784/>
                    <Frame281>
                      <Menu>
                        Playground
                      </Menu>
                    </Frame281>
                    <Indicator/>
                  </BaseHeaderPrimaryMenu_0001>
                </BaseHeaderPrimaryMenu>
                <BaseHeaderPrimaryMenu>
                  <BaseHeaderPrimaryMenu_0001>
                    <Rectangle784/>
                    <Frame281>
                      <Menu>
                        Pricing
                      </Menu>
                    </Frame281>
                    <Indicator/>
                  </BaseHeaderPrimaryMenu_0001>
                </BaseHeaderPrimaryMenu>
                <BaseHeaderPrimaryMenu>
                  <BaseHeaderPrimaryMenu_0001>
                    <Rectangle784/>
                    <Frame281>
                      <Menu>
                        Github
                      </Menu>
                    </Frame281>
                    <Indicator/>
                  </BaseHeaderPrimaryMenu_0001>
                </BaseHeaderPrimaryMenu>
              </Menus>
            </Leading>
            <HeaderCtaSignupPlain>
              <HeaderCtaSignupPlain_0001>
                <SignUp>
                  Get started
                </SignUp>
              </HeaderCtaSignupPlain_0001>
            </HeaderCtaSignupPlain>
          </Frame33>
        </Appbar>
      </Frame566>
      <Group484>
        <Frame497>
          <Frame496>
            <Frame495>
              <ForPersonalProjects>
                For Personal Projects
              </ForPersonalProjects>
              <Frame486>
                <_4>
                  $4
                </_4>
                <Month>
                  / Month
                </Month>
              </Frame486>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e65f4471-310b-48e9-b57e-c95a7b34e906" />
                <FeatureName>
                  1,000,000 requests per month
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b9149ef7-2e3f-4361-9207-db13c9608092" />
                <FeatureName>
                  500GB Bandwidth
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/85e101a3-23ef-4a90-8067-a34f959fe848" />
                <FeatureName>
                  Unlimited Sites
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3d746ce4-0add-4694-9355-7b9792a3c3b3" />
                <FeatureName>
                  Max 6mb per request
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d2ab6a89-4a2f-49d5-99de-344b9c140f22" />
                <FeatureName>
                  Unlimited requests per hour
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7f0a6bae-954b-4179-b4b7-25f9a6eb4758" />
                <FeatureName>
                  No down time
                </FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>
              Get started
            </Label>
          </Button>
        </Frame497>
      </Group484>
      <Group483>
        <Frame497>
          <Frame496>
            <Frame495>
              <ForYourTeam>
                For your team
              </ForYourTeam>
              <Frame486_0001>
                <PayAsYouGo>
                  Pay as you go
                </PayAsYouGo>
                <From10PerMonth>
                  From $10 per month
                </From10PerMonth>
              </Frame486_0001>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/30316f5c-1351-4d69-999d-9ab525c60d78" />
                <FeatureName_0006>
                  1,000,000 requests / month included
                </FeatureName_0006>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a6371d23-17d1-4cc8-b48b-8ae30299e9df" />
                <FeatureName>
                  Unlimited traffic
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d6f72b5a-df2d-4058-9da6-a4e4ae58a028" />
                <FeatureName_0006>
                  $1 per every next 100,000 requests
                </FeatureName_0006>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/897b5350-b93d-4079-8871-1bd725f77eb5" />
                <FeatureName>
                  Unlimited Applications
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/924887e7-8f5a-44b3-a379-6e2b3a28a722" />
                <FeatureName>
                  Max 6mb per request
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/29af5e20-0191-44fd-9e34-593b7cad270d" />
                <FeatureName>
                  Unlimited requests per hour
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d3a5606e-bcdf-4717-b6d8-f420ebabbeb5" />
                <FeatureName>
                  No down time
                </FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>
              Get started
            </Label>
          </Button>
        </Frame497>
      </Group483>
      <Group485>
        <Frame497>
          <Frame496>
            <Frame495>
              <HobbyTesting>
                Hobby & Testing
              </HobbyTesting>
              <Frame486_0001>
                <_4>
                  $0
                </_4>
              </Frame486_0001>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e239e4d7-fd2c-4748-b6a7-cd3adf92ac31" />
                <FeatureName>
                  10,000 requests per month
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4e34d4b7-897a-45af-bd47-ef085995dd2b" />
                <FeatureName>
                  5GB traffic per month
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/00f11ca0-9736-4449-8d79-39e588e2fbc4" />
                <FeatureName>
                  500 requests per hour
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/566b723a-e3ae-4456-9479-9de53f92d341" />
                <FeatureName>
                  3 Applications
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ce6850b9-91e4-4c10-9864-881c24e3a072" />
                <FeatureName>
                  3mb per request
                </FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c3c30156-f923-43dd-a468-b5e38b6e0d61" />
                <FeatureName>
                  No down time
                </FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>
              Get started
            </Label>
          </Button>
        </Frame497>
      </Group485>
      <Frame571>
        <Frame549>
          <EnterYourEmailAddress>
            Enter your email address
          </EnterYourEmailAddress>
        </Frame549>
        <Frame550_0001>
          <Frame556_0001>
            <SendMeAnApiKey>
              Send me an API Key
            </SendMeAnApiKey>
          </Frame556_0001>
        </Frame550_0001>
      </Frame571>
      <SectionCtaLastSeeTheMagic>
        <Frame270>
          <SayByeToCorsErrors>
            Say bye to cors errors
          </SayByeToCorsErrors>
          <AndFocusOnYouReDevelopment>
            And focus on you’re development
          </AndFocusOnYouReDevelopment>
        </Frame270>
        <ScribbleGuide>
          <WeLlSendYouAApiKeyToGetStarted>
            We’ll send you a Api key to get started
          </WeLlSendYouAApiKeyToGetStarted>
          <PointerArtwork src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0d147f5c-c16e-43f9-832c-77a02a265cff" alt="image of PointerArtwork"/>
        </ScribbleGuide>
        <Frame572>
          <Frame549>
            <EnterYourEmailAddress>
              Enter your email address
            </EnterYourEmailAddress>
          </Frame549>
          <Frame550_0001>
            <Frame556_0001>
              <SendMeAnApiKey>
                Send me an API Key
              </SendMeAnApiKey>
            </Frame556_0001>
          </Frame550_0001>
        </Frame572>
      </SectionCtaLastSeeTheMagic>
      <FreePricingHeroCardLarge>
        <Frame315>
          <Frame247>
            <Frame246>
              <PricelistFeatureItemFeatured>
                <Frame245 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/996c4f36-f27e-43d9-b6d9-1163922a8cd2" alt="icon"/>
                <FeatureName_0019>
                  1,000,000 requests / month
                </FeatureName_0019>
              </PricelistFeatureItemFeatured>
              <Component7>
                <Frame245 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/be883eac-0478-4328-9e48-ca254bd3dfbb" alt="icon"/>
                <FeatureName_0019>
                  5mb per request
                </FeatureName_0019>
              </Component7>
              <PricelistFeatureItemFeatured>
                <Frame245 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/33edb42e-a87b-437f-923c-4a184f047e65" alt="icon"/>
                <FeatureName_0019>
                  Unlimited requests per hour
                </FeatureName_0019>
              </PricelistFeatureItemFeatured>
              <Component7>
                <Frame245 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/02389931-9fcb-4179-a1af-8adfc5841d15" alt="icon"/>
                <FeatureName_0019>
                  No down time
                </FeatureName_0019>
              </Component7>
            </Frame246>
          </Frame247>
          <Frame314>
            <Frame313>
              <Frame244>
                <Free>
                  Free
                </Free>
                <ForOpenSource>
                   for Open Source
                </ForOpenSource>
              </Frame244>
              <Frame312>
                <Button_0003>
                  <Label>
                    Apply
                  </Label>
                </Button_0003>
                <LimitedToPublicProjectsThatAreOnGithub>
                  *Limited to Public Projects that are on Github
                </LimitedToPublicProjectsThatAreOnGithub>
              </Frame312>
            </Frame313>
          </Frame314>
        </Frame315>
      </FreePricingHeroCardLarge>
      <Line35/>
      <Frame573>
        <Frame575>
          <Frame574 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c7446de5-b39b-4ce2-8058-90372e91e9ec" alt="icon"/>
        </Frame575>
        <FetchSuccess>
          Fetch success!
        </FetchSuccess>
      </Frame573>
      <Frame581>
        <Frame575>
          <Frame574 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ddd4cfab-5a29-41d8-8aba-03237b09a567" alt="icon"/>
        </Frame575>
        <ConnectToYourDevServer>
          Connect to your dev server
        </ConnectToYourDevServer>
      </Frame581>
      <Frame582>
        <Frame575>
          <Frame574 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bbbf1247-311e-462c-b670-62335cabd8fa" alt="icon"/>
        </Frame575>
        <FetchImagesFromInstagram>
          Fetch images from instagram
        </FetchImagesFromInstagram>
      </Frame582>
      <Frame578>
        <Frame575>
          <Frame574 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1fc33483-d632-43f4-9a60-6e8ec9a3a7f6" alt="icon"/>
        </Frame575>
        <AccessToFetchAtHttpsTargetDomainFromOriginHttpsMySiteHasBeenBlockedByCorsPolicyNoAccessControlAllowOriginHeaderIsPresentOnTheRequestedResourceIfAnOpaqueResponseServesYourNeedsSetTheRequestSModeToNoCorsToFetchTheResourceWithCorsDisabled>
          Access to fetch at ‘https://target.domain’ from origin ‘https://my.site’ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on the requested resource. If an opaque response serves your needs, set the request’s mode to ‘no-cors’ to fetch the resource with CORS disabled.
        </AccessToFetchAtHttpsTargetDomainFromOriginHttpsMySiteHasBeenBlockedByCorsPolicyNoAccessControlAllowOriginHeaderIsPresentOnTheRequestedResourceIfAnOpaqueResponseServesYourNeedsSetTheRequestSModeToNoCorsToFetchTheResourceWithCorsDisabled>
      </Frame578>
      <Disclaimer>
        DISCLAIMER
      </Disclaimer>
      <_1CorsShIsAMirrorServicesForTheOriginalProjectCorsAnywhereByRobWBothProjectIsLicensedUnderMitAsOfSeptember20222RevenueSharingTheRevenueByCorsShWillBeDistributedBackToOriginalAuthors3AsOf31March2022IncludesLocationOfEmployeesContractorsAndConsultants4AsOf31March2022AllFiguresAreBasedOnInternalDataAndThirdPartyDataWhichMayNotHaveBeenExternallyVerifiedPortfolioCompaniesDisplayedOnThisPageAreNotNecessarilyRepresentativeOfAllInvestmentsInVehiclesManagedBy500StartupsManagementCompanyLlcTogetherWithItsAffiliates500GlobalAndThereCanBeNoAssuranceThatTheInvestmentsWillBeProfitableOrThatOtherInvestmentsMadeInTheFutureWillHaveSimilarCharacteristicsOrResultsThisListIncludesCurrentAndFormer500GlobalPortfolioCompaniesWhichHaveBeenAcquiredAsWellAsCompaniesWhichHaveUndergoneAnInitialPublicOfferingThisListIsUpdatedPeriodicallyAndAsSuchMayNotReflectRecent500GlobalInvestmentsPastResultsOf500GlobalInvestmentsPooledInvestmentVehiclesOrInvestmentStrategiesAreNotNecessarilyIndicativeOfFutureResultsNoContentOnThisPageShouldBeConsideredAsAnOfferToSellOrSolicitationOfInterestToPurchaseAnySecuritiesConstructedAsFundMarketingMaterialsByProspectiveInvestorsConsideringAnInvestmentIntoAny500GlobalFundOrUsedAsTheBasisForAnyInvestmentDecisionsAllLogosNamesAndTrademarksOfThirdPartiesReferencedHereinAreTheTrademarksAndLogosOfTheirRespectiveOwnersAnyInclusionOfSuchTrademarksOrLogosDoesNotImplyOrConstituteAnyApprovalEndorsementOrSponsorshipOf500GlobalBySuchOwners>
        1. CORS.SH is a mirror services for the original project cors-anywhere by Rob--W. Both project is licensed under MIT as of September 2022.<br/>
<br/>
2. Revenue sharing. The revenue by cors.sh will be distributed back to original authors<br/>
<br/>
3. AS OF 31 MARCH 2022. INCLUDES LOCATION OF EMPLOYEES, CONTRACTORS AND CONSULTANTS.<br/>
<br/>
4. AS OF 31 MARCH 2022. ALL FIGURES ARE BASED ON INTERNAL DATA AND THIRD PARTY DATA WHICH MAY NOT HAVE BEEN EXTERNALLY VERIFIED. PORTFOLIO COMPANIES DISPLAYED ON THIS PAGE ARE NOT NECESSARILY REPRESENTATIVE OF ALL INVESTMENTS IN VEHICLES MANAGED BY 500 STARTUPS MANAGEMENT COMPANY, L.L.C. (TOGETHER WITH ITS AFFILIATES, “500 GLOBAL”) AND THERE CAN BE NO ASSURANCE THAT THE INVESTMENTS WILL BE PROFITABLE OR THAT OTHER INVESTMENTS MADE IN THE FUTURE WILL HAVE SIMILAR CHARACTERISTICS OR RESULTS. THIS LIST INCLUDES CURRENT AND FORMER 500 GLOBAL PORTFOLIO COMPANIES WHICH HAVE BEEN ACQUIRED AS WELL AS COMPANIES WHICH HAVE UNDERGONE AN INITIAL PUBLIC OFFERING. THIS LIST IS UPDATED PERIODICALLY AND AS SUCH MAY NOT REFLECT RECENT 500 GLOBAL INVESTMENTS. PAST RESULTS OF 500 GLOBAL INVESTMENTS, POOLED INVESTMENT VEHICLES, OR INVESTMENT STRATEGIES ARE NOT NECESSARILY INDICATIVE OF FUTURE RESULTS. NO CONTENT ON THIS PAGE SHOULD BE CONSIDERED AS AN OFFER TO SELL OR SOLICITATION OF INTEREST TO PURCHASE ANY SECURITIES, CONSTRUCTED AS FUND MARKETING MATERIALS BY PROSPECTIVE INVESTORS CONSIDERING AN INVESTMENT INTO ANY 500 GLOBAL FUND, OR USED AS THE BASIS FOR ANY INVESTMENT DECISIONS. ALL LOGOS, NAMES, AND TRADEMARKS OF THIRD PARTIES REFERENCED HEREIN ARE THE TRADEMARKS AND LOGOS OF THEIR RESPECTIVE OWNERS. ANY INCLUSION OF SUCH TRADEMARKS OR LOGOS DOES NOT IMPLY OR CONSTITUTE ANY APPROVAL, ENDORSEMENT OR SPONSORSHIP OF 500 GLOBAL BY SUCH OWNERS.
      </_1CorsShIsAMirrorServicesForTheOriginalProjectCorsAnywhereByRobWBothProjectIsLicensedUnderMitAsOfSeptember20222RevenueSharingTheRevenueByCorsShWillBeDistributedBackToOriginalAuthors3AsOf31March2022IncludesLocationOfEmployeesContractorsAndConsultants4AsOf31March2022AllFiguresAreBasedOnInternalDataAndThirdPartyDataWhichMayNotHaveBeenExternallyVerifiedPortfolioCompaniesDisplayedOnThisPageAreNotNecessarilyRepresentativeOfAllInvestmentsInVehiclesManagedBy500StartupsManagementCompanyLlcTogetherWithItsAffiliates500GlobalAndThereCanBeNoAssuranceThatTheInvestmentsWillBeProfitableOrThatOtherInvestmentsMadeInTheFutureWillHaveSimilarCharacteristicsOrResultsThisListIncludesCurrentAndFormer500GlobalPortfolioCompaniesWhichHaveBeenAcquiredAsWellAsCompaniesWhichHaveUndergoneAnInitialPublicOfferingThisListIsUpdatedPeriodicallyAndAsSuchMayNotReflectRecent500GlobalInvestmentsPastResultsOf500GlobalInvestmentsPooledInvestmentVehiclesOrInvestmentStrategiesAreNotNecessarilyIndicativeOfFutureResultsNoContentOnThisPageShouldBeConsideredAsAnOfferToSellOrSolicitationOfInterestToPurchaseAnySecuritiesConstructedAsFundMarketingMaterialsByProspectiveInvestorsConsideringAnInvestmentIntoAny500GlobalFundOrUsedAsTheBasisForAnyInvestmentDecisionsAllLogosNamesAndTrademarksOfThirdPartiesReferencedHereinAreTheTrademarksAndLogosOfTheirRespectiveOwnersAnyInclusionOfSuchTrademarksOrLogosDoesNotImplyOrConstituteAnyApprovalEndorsementOrSponsorshipOf500GlobalBySuchOwners>
      <Footer>
        <Frame223>
          <Frame221>
            <Logo64_0001>
              <LogoShapeOnly_0001>
                <Union_0001 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f171a66e-b573-432d-843c-62e27b39f480" alt="image of Union"/>
              </LogoShapeOnly_0001>
            </Logo64_0001>
            <Frame220>
              <Frame201>
                <Products>
                  Products
                </Products>
                <Frame200>
                  <Cloud>
                    Cloud
                  </Cloud>
                  <Globalization>
                    Globalization
                  </Globalization>
                  <Reflect>
                    Reflect
                  </Reflect>
                  <Surf>
                    Surf
                  </Surf>
                  <Assistant>
                    Assistant
                  </Assistant>
                  <Console>
                    Console
                  </Console>
                  <Appbox>
                    Appbox
                  </Appbox>
                </Frame200>
              </Frame201>
              <Frame201>
                <Solutions>
                  Solutions
                </Solutions>
                <Frame200>
                  <Handoff>
                    Handoff
                  </Handoff>
                  <GetStarted>
                    Get started
                  </GetStarted>
                  <ApiDocs>
                    API Docs
                  </ApiDocs>
                  <Papers>
                    Papers
                  </Papers>
                  <Games>
                    Games
                  </Games>
                  <Showcase>
                    Showcase
                  </Showcase>
                </Frame200>
              </Frame201>
              <Frame201>
                <Resources>
                  Resources
                </Resources>
                <Frame200>
                  <Docs>
                    Docs
                  </Docs>
                  <GetStarted>
                    Get started
                  </GetStarted>
                  <ApiDocs>
                    API Docs
                  </ApiDocs>
                  <Papers>
                    Papers
                  </Papers>
                  <Blogs>
                    Blogs
                  </Blogs>
                  <Showcase>
                    Showcase
                  </Showcase>
                  <Mockups>
                    Mockups
                  </Mockups>
                  <ClickclickDesign>
                    clickclick.design
                  </ClickclickDesign>
                </Frame200>
              </Frame201>
              <Frame201>
                <Platforms>
                  Platforms
                </Platforms>
                <Frame200>
                  <Figma>
                    Figma
                  </Figma>
                  <Sketch>
                    Sketch
                  </Sketch>
                  <Xd>
                    XD
                  </Xd>
                  <React_0001>
                    React
                  </React_0001>
                  <Flutter>
                    Flutter
                  </Flutter>
                  <Vue>
                    Vue
                  </Vue>
                  <Svelte>
                    Svelte
                  </Svelte>
                  <HtmlCss>
                    HTML/CSS
                  </HtmlCss>
                  <Reflect>
                    Reflect
                  </Reflect>
                  <Unity>
                    Unity
                  </Unity>
                  <Unreal>
                    Unreal
                  </Unreal>
                </Frame200>
              </Frame201>
              <Frame201>
                <Together>
                  Together
                </Together>
                <Frame200>
                  <AboutUs>
                    About us
                  </AboutUs>
                  <LetSCreateTogether>
                    Let’s create together
                  </LetSCreateTogether>
                  <ProejctBy>
                    Proejct - BY
                  </ProejctBy>
                  <Github>
                    Github
                  </Github>
                  <Projects>
                    Projects
                  </Projects>
                  <JoinUsOnSlack>
                    Join us on Slack
                  </JoinUsOnSlack>
                  <Meetups>
                    Meetups
                  </Meetups>
                  <Reddit>
                    Reddit
                  </Reddit>
                </Frame200>
              </Frame201>
            </Frame220>
          </Frame221>
          <Frame246>
            <Line34/>
            <Frame205>
              <IconsAntdYoutubeDefault src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e4ec4da0-beb9-4c56-99a8-6179d25c7e81" alt="icon"/>
              <IconsAntdInstagramDefault src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ed6a7c87-f6bc-488e-93a1-2c6c427ae5eb" alt="icon"/>
              <IconsAntdTwitterOutlined src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b6347077-a4bf-47f4-99c4-26b0ee026557" alt="icon"/>
              <IconsMdiFacebook src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4652487a-ee42-4b00-92fe-c177025ecc83" />
              <IconsAntdDribbbleCircleDefault src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b9a0f77b-1814-435b-8d7b-c4ea29e95a8f" alt="icon"/>
              <IconsAntdGithubDefault src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/26aa4f94-f980-4039-87d5-9e26bc0ea0b5" alt="icon"/>
            </Frame205>
            <Frame248>
              <Copyright2021GridaCo>
                Copyright © 2021 Grida.co
              </Copyright2021GridaCo>
              <Frame243>
                <Cookies>
                  Cookies
                </Cookies>
                <PrivacyPolicy>
                  Privacy policy
                </PrivacyPolicy>
                <TermsAndConditions>
                  Terms and conditions
                </TermsAndConditions>
              </Frame243>
            </Frame248>
          </Frame246>
        </Frame223>
      </Footer>
      <GetHttpsCorsShHttpsInstagramCom>
        GET https://cors.sh/https://instagram.com
      </GetHttpsCorsShHttpsInstagramCom>
    </RootWrapperCorsSh>
  )
}

const RootWrapperCorsSh = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Frame580 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 10px;
	box-shadow: 0px 4px 24px  rgba(0, 0, 0, 0.25);
	border: solid 1px black;
	border-radius: 4px;
	background-color: rgba(0, 0, 0, 0.49);
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: calc((calc((50% + 5px)) - 247px));
	top: 1904px;
	width: 494px;
	height: 41px;
`;

const Frame575 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-sizing: border-box;
	padding: 4px 0px 0px;
`;

const Frame574 = styled.img`
	width: 15px;
	height: 15px;
	object-fit: cover;
`;

const FetchImagesFromInstagram = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Source Code Pro", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 119%;
	text-align: left;
	width: 451px;
	flex: 1;
`;

const Frame577 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 32px;
	box-sizing: border-box;
	position: absolute;
	left: 200px;
	top: 319px;
	width: 551px;
	height: 256px;
`;

const SickOfCorsErrors = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 80px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	letter-spacing: -2px;
	line-height: 98%;
	text-align: left;
	width: 553px;
`;

const AFastReliableCorsProxyForYourWebsites = styled.span`
	color: rgba(0, 0, 0, 0.6);
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	line-height: 160%;
	text-align: left;
	width: 356px;
`;

const SimpleUsage = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 64px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	line-height: 98%;
	text-align: center;
	position: absolute;
	left: 514px;
	top: 1250px;
`;

const YouCanUseTheProxyServiceBySimplyAddingHttpsCorsShToYourExistingApi = styled.span`
	color: rgba(0, 0, 0, 0.6);
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	line-height: 160%;
	text-align: center;
	width: 489px;
	position: absolute;
	left: 476px;
	top: 1353px;
`;

const Pricing = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 64px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	line-height: 98%;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 1px)) - 108px));
	top: 3008px;
`;

const Frame560 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	box-shadow: 0px 4px 24px  rgba(0, 0, 0, 0.04);
	border: solid 1px rgba(0, 0, 0, 0.1);
	border-radius: 4px;
	background-color: white;
	box-sizing: border-box;
	padding: 10px 20px;
	position: absolute;
	left: 468px;
	top: 1585px;
	width: 136px;
	height: 105px;
`;

const Frame579 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	box-shadow: 0px 4px 24px  rgba(0, 0, 0, 0.04);
	border: solid 1px rgba(0, 0, 0, 0.1);
	border-radius: 4px;
	background-color: white;
	box-sizing: border-box;
	padding: 10px 20px;
	position: absolute;
	left: 818px;
	top: 1585px;
	width: 136px;
	height: 105px;
`;

const Image2 = styled.img`
	width: 40px;
	height: 40px;
	object-fit: cover;
`;

const Frame4 = styled.div`
	width: 1040px;
	height: 365px;
	overflow: hidden;
	background-color: white;
	border: solid 1px rgba(0, 0, 0, 0.1);
	border-radius: 4px;
	position: absolute;
	left: 200px;
	top: 2186px;
`;

const GetHttpsCorshShHttpsInstragramComPosts123HApiKeyGetYourApiKey = styled.span`
	color: rgb(68, 68, 68);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 70px;
	top: 96px;
`;

const CUrl = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	position: absolute;
	left: 70px;
	top: 38px;
`;

const Js = styled.span`
	color: rgba(0, 0, 0, 0.2);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	position: absolute;
	left: 128px;
	top: 38px;
`;

const Sdk = styled.span`
	color: rgba(0, 0, 0, 0.2);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	position: absolute;
	left: 164px;
	top: 38px;
`;

const ViewAllExamples = styled.span`
	color: rgb(215, 215, 215);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	text-align: left;
	position: absolute;
	left: 860px;
	top: 318px;
`;

const Frame555 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 14px;
	box-sizing: border-box;
	position: absolute;
	left: 200px;
	top: 665px;
	width: 673px;
	height: 66px;
`;

const Frame549 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 4px 48px  rgba(0, 0, 0, 0.12);
	border: solid 1px rgb(210, 210, 210);
	border-radius: 4px;
	width: 508px;
	background-color: white;
	box-sizing: border-box;
	padding: 24px;
`;

const HttpsExampleCom = styled.span`
	color: rgb(181, 181, 181);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

const Frame550 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 4px 48px  rgba(0, 0, 0, 0.12);
	border: solid 1px rgb(210, 210, 210);
	border-radius: 4px;
	width: 151px;
	height: 66px;
	background-color: black;
	box-sizing: border-box;
	padding-left: 12px;
	padding-right: 4px;
`;

const Frame551 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 8px;
	align-self: stretch;
	height: 66px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame556 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 10px;
	align-self: stretch;
	width: 99px;
	box-sizing: border-box;
	padding: 10px;
	flex-shrink: 0;
`;

const Get = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

const Frame30 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 4px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Line6 = styled.div`
	width: 66px;
	border-top: solid 1px rgba(255, 255, 255, 0.37);
	align-self: stretch;
	flex-shrink: 0;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const IconsMdiArrowDropDown = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Frame570 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 138px;
	box-sizing: border-box;
	position: absolute;
	left: 200px;
	top: 851px;
	width: 956px;
	height: 24px;
`;

const Frame562 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 15px;
	box-sizing: border-box;
`;

const Frame561 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Secure = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Reliable = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Fast = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const ACorsAnywhereMirror = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Frame566 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	box-sizing: border-box;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	height: 130px;
`;

const Frame565 = styled.div`
	height: 50px;
	overflow: hidden;
	background-color: black;
	position: relative;
	align-self: stretch;
	flex-shrink: 0;
`;

const Home = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 8px;
	box-sizing: border-box;
	position: absolute;
	left: 200px;
	top: 12px;
	width: 171px;
	height: 26px;
`;

const Logo64 = styled.div`
	width: 25px;
	height: 26px;
	overflow: hidden;
	position: relative;
`;

const LogoShapeOnly = styled.div`
	width: 25px;
	height: 25px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Union = styled.img`
	width: 25px;
	height: 25px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const GridaAppServices = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Helvetica, sans-serif;
	font-weight: 700;
	letter-spacing: -1px;
	text-align: left;
`;

const Appbar = styled.div`
	height: 80px;
	background-color: white;
	position: relative;
	align-self: stretch;
	flex-shrink: 0;
`;

const Frame33 = styled.div`
	width: 1040px;
	overflow: hidden;
	position: absolute;
	left: calc((calc((50% + 0px)) - 520px));
	top: 0px;
	bottom: 0px;
`;

const Leading = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 120px;
	box-sizing: border-box;
	position: absolute;
	left: 0px;
	top: calc((calc((50% + 0px)) - 30px));
	width: 732px;
	height: 60px;
`;

const Home_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const CorsSh_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Inter, sans-serif;
	font-weight: 900;
	letter-spacing: -1px;
	text-align: left;
`;

const Menus = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 36px;
	height: 60px;
	box-sizing: border-box;
`;

const BaseHeaderPrimaryMenu = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	box-sizing: border-box;
`;

const BaseHeaderPrimaryMenu_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 16px;
	box-sizing: border-box;
`;

const Rectangle784 = styled.div`
	height: 2px;
	background-color: white;
	align-self: stretch;
	flex-shrink: 0;
	opacity: 0;
`;

const Frame281 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	box-sizing: border-box;
`;

const Menu = styled.span`
	color: rgb(139, 139, 139);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	text-align: left;
`;

const Indicator = styled.div`
	height: 2px;
	background-color: rgba(0, 0, 0, 0);
	align-self: stretch;
	flex-shrink: 0;
	opacity: 0;
`;

const HeaderCtaSignupPlain = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	position: absolute;
	top: calc((calc((50% + 0px)) - 16px));
	right: 0px;
	width: 80px;
	height: 32px;
`;

const HeaderCtaSignupPlain_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	border-radius: 35px;
	box-sizing: border-box;
`;

const SignUp = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	text-align: right;
`;

const Group484 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 10px;
	box-shadow: 0px 4px 128px 32px rgba(0, 0, 0, 0.08);
	border-radius: 8px;
	background-color: white;
	box-sizing: border-box;
	padding: 40px;
	position: absolute;
	left: 530px;
	top: 3180px;
	width: 380px;
	height: 673px;
`;

const Frame497 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: 1;
	gap: 142px;
	width: 300px;
	box-sizing: border-box;
`;

const Frame496 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 72px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame495 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 36px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const ForPersonalProjects = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	line-height: 135%;
	text-align: left;
	align-self: stretch;
	flex-shrink: 0;
`;

const Frame486 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 16px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const _4 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 36px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	line-height: 135%;
	text-align: left;
`;

const Month = styled.span`
	color: rgba(109, 109, 109, 0.83);
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Frame310 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 16px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const PricelistFeatureItem = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 8px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const IconsMdiCheck = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const FeatureName = styled.span`
	color: rgb(83, 83, 83);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 270px;
	flex: 1;
`;

const Button = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	border: solid 1px rgb(28, 28, 28);
	border-radius: 4px;
	align-self: stretch;
	background-color: black;
	box-sizing: border-box;
	padding: 12px 89px;
	flex-shrink: 0;
`;

const Label = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	text-align: left;
`;

const Group483 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 24px;
	border: solid 1px rgb(246, 246, 246);
	border-radius: 8px;
	background-color: rgb(252, 252, 252);
	box-sizing: border-box;
	padding: 40px;
	position: absolute;
	left: 936px;
	top: 3179px;
	width: 380px;
	height: 713px;
`;

const ForYourTeam = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	line-height: 135%;
	text-align: left;
	align-self: stretch;
	flex-shrink: 0;
`;

const Frame486_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 16px;
	align-self: stretch;
	height: 49px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const PayAsYouGo = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 36px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	line-height: 135%;
	text-align: left;
`;

const From10PerMonth = styled.span`
	color: rgba(109, 109, 109, 0.83);
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 261px;
`;

const FeatureName_0006 = styled.span`
	color: rgb(83, 83, 83);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 268px;
	flex: 1;
`;

const Group485 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 24px;
	border: solid 1px rgb(246, 246, 246);
	border-radius: 8px;
	background-color: rgb(252, 252, 252);
	box-sizing: border-box;
	padding: 40px;
	position: absolute;
	left: 124px;
	top: 3179px;
	width: 380px;
	height: 673px;
`;

const HobbyTesting = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	line-height: 135%;
	text-align: left;
	align-self: stretch;
	flex-shrink: 0;
`;

const Frame571 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 14px;
	box-sizing: border-box;
	position: absolute;
	left: 348px;
	top: 2706px;
	width: 745px;
	height: 66px;
`;

const EnterYourEmailAddress = styled.span`
	color: rgb(181, 181, 181);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

const Frame550_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 4px 48px  rgba(0, 0, 0, 0.12);
	border: solid 1px rgb(210, 210, 210);
	border-radius: 4px;
	height: 66px;
	background-color: black;
	box-sizing: border-box;
	padding: 0px 21px;
`;

const Frame556_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	height: 66px;
	box-sizing: border-box;
	padding: 10px;
	flex-shrink: 0;
`;

const SendMeAnApiKey = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

const SectionCtaLastSeeTheMagic = styled.div`
	height: 663px;
	overflow: hidden;
	background-color: white;
	position: absolute;
	left: 0px;
	top: 4758px;
	right: 0px;
`;

const Frame270 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 36px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + -1px)) - 337px));
	top: 105px;
	width: 673px;
	height: 137px;
`;

const SayByeToCorsErrors = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 64px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	line-height: 98%;
	text-align: center;
`;

const AndFocusOnYouReDevelopment = styled.span`
	color: rgb(68, 69, 69);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	line-height: 160%;
	text-align: center;
	align-self: stretch;
	flex-shrink: 0;
`;

const ScribbleGuide = styled.div`
	width: 217px;
	height: 112px;
	position: absolute;
	left: 235px;
	top: 302px;
`;

const WeLlSendYouAApiKeyToGetStarted = styled.span`
	color: rgb(164, 164, 164);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: "Nanum Pen Script", sans-serif;
	font-weight: 400;
	line-height: 98%;
	text-align: left;
	width: 213px;
	position: absolute;
	left: calc((calc((50% + -2px)) - 107px));
	top: 25px;
	transform: rotate(-7deg);
	transform-origin: top left;
`;

const PointerArtwork = styled.img`
	width: 53px;
	height: 69px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 59px)) - 26px));
	top: 49px;
	transform: rotate(-23deg);
	transform-origin: top left;
`;

const Frame572 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 14px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + -1px)) - 373px));
	top: 414px;
	width: 745px;
	height: 66px;
`;

const FreePricingHeroCardLarge = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	gap: 10px;
	box-shadow: 0px 4px 64px 12px rgba(0, 0, 0, 0.08);
	border-radius: 8px;
	background-color: white;
	box-sizing: border-box;
	position: absolute;
	left: 201px;
	top: 4044px;
	width: 1040px;
	height: 312px;
`;

const Frame315 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame247 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	flex: 1;
	gap: 10px;
	border-radius: 8px;
	width: 520px;
	background-color: rgb(252, 252, 252);
	box-sizing: border-box;
	padding: 56px;
`;

const Frame246 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 24px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const PricelistFeatureItemFeatured = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 16px;
	align-self: stretch;
	height: 32px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame245 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const FeatureName_0019 = styled.span`
	color: rgb(94, 94, 94);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Component7 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 16px;
	align-self: stretch;
	height: 32px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame314 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: 1;
	gap: 10px;
	width: 520px;
	background-color: white;
	box-sizing: border-box;
	padding: 31px 72px;
`;

const Frame313 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 24px;
	box-sizing: border-box;
`;

const Frame244 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: flex-end;
	flex: none;
	gap: 4px;
	box-sizing: border-box;
`;

const Free = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 42px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	text-align: left;
`;

const ForOpenSource = styled.span`
	color: rgb(99, 99, 99);
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Frame312 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 14px;
	box-sizing: border-box;
`;

const Button_0003 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	border: solid 1px rgb(28, 28, 28);
	border-radius: 4px;
	width: 337px;
	background-color: black;
	box-sizing: border-box;
	padding: 12px 89px;
`;

const LimitedToPublicProjectsThatAreOnGithub = styled.span`
	color: rgb(154, 154, 154);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	line-height: 135%;
	text-align: left;
`;

const Line35 = styled.div`
	width: 1039px;
	height: 0px;
	border-top: solid 1px rgba(0, 0, 0, 0.1);
	position: absolute;
	left: 201px;
	top: 3968px;
`;

const Frame573 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 10px;
	box-shadow: 0px 4px 24px  rgba(0, 0, 0, 0.25);
	border: solid 1px rgb(0, 71, 255);
	border-radius: 4px;
	background-color: rgba(0, 56, 255, 0.49);
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: calc((calc((50% + 5px)) - 247px));
	top: 1792px;
	width: 494px;
	height: 41px;
`;

const FetchSuccess = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Source Code Pro", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 119%;
	text-align: left;
	width: 451px;
	flex: 1;
`;

const Frame581 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 10px;
	box-shadow: 0px 4px 24px  rgba(0, 0, 0, 0.25);
	border: solid 1px black;
	border-radius: 4px;
	background-color: rgba(0, 0, 0, 0.49);
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: calc((calc((50% + 5px)) - 247px));
	top: 1958px;
	width: 494px;
	height: 41px;
`;

const ConnectToYourDevServer = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Source Code Pro", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 119%;
	text-align: left;
	width: 451px;
	flex: 1;
`;

const Frame582 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 10px;
	box-shadow: 0px 4px 24px  rgba(0, 0, 0, 0.25);
	border: solid 1px black;
	border-radius: 4px;
	background-color: rgba(0, 0, 0, 0.49);
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: calc((calc((50% + 5px)) - 247px));
	top: 2010px;
	width: 494px;
	height: 41px;
`;

const Frame578 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 10px;
	box-shadow: 0px 4px 32px  rgba(255, 0, 0, 0.08);
	border: solid 1px rgb(255, 46, 46);
	border-radius: 4px;
	background-color: rgb(252, 240, 240);
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: calc((calc((50% + 351px)) - 245px));
	top: 345px;
	width: 490px;
	height: 167px;
`;

const AccessToFetchAtHttpsTargetDomainFromOriginHttpsMySiteHasBeenBlockedByCorsPolicyNoAccessControlAllowOriginHeaderIsPresentOnTheRequestedResourceIfAnOpaqueResponseServesYourNeedsSetTheRequestSModeToNoCorsToFetchTheResourceWithCorsDisabled = styled.span`
	color: rgb(233, 22, 6);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Source Code Pro", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 119%;
	text-align: left;
	width: 445px;
	flex: 1;
`;

const Disclaimer = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Roboto Mono", sans-serif;
	font-weight: 500;
	text-align: center;
	position: absolute;
	left: 666px;
	top: 5644px;
`;

const _1CorsShIsAMirrorServicesForTheOriginalProjectCorsAnywhereByRobWBothProjectIsLicensedUnderMitAsOfSeptember20222RevenueSharingTheRevenueByCorsShWillBeDistributedBackToOriginalAuthors3AsOf31March2022IncludesLocationOfEmployeesContractorsAndConsultants4AsOf31March2022AllFiguresAreBasedOnInternalDataAndThirdPartyDataWhichMayNotHaveBeenExternallyVerifiedPortfolioCompaniesDisplayedOnThisPageAreNotNecessarilyRepresentativeOfAllInvestmentsInVehiclesManagedBy500StartupsManagementCompanyLlcTogetherWithItsAffiliates500GlobalAndThereCanBeNoAssuranceThatTheInvestmentsWillBeProfitableOrThatOtherInvestmentsMadeInTheFutureWillHaveSimilarCharacteristicsOrResultsThisListIncludesCurrentAndFormer500GlobalPortfolioCompaniesWhichHaveBeenAcquiredAsWellAsCompaniesWhichHaveUndergoneAnInitialPublicOfferingThisListIsUpdatedPeriodicallyAndAsSuchMayNotReflectRecent500GlobalInvestmentsPastResultsOf500GlobalInvestmentsPooledInvestmentVehiclesOrInvestmentStrategiesAreNotNecessarilyIndicativeOfFutureResultsNoContentOnThisPageShouldBeConsideredAsAnOfferToSellOrSolicitationOfInterestToPurchaseAnySecuritiesConstructedAsFundMarketingMaterialsByProspectiveInvestorsConsideringAnInvestmentIntoAny500GlobalFundOrUsedAsTheBasisForAnyInvestmentDecisionsAllLogosNamesAndTrademarksOfThirdPartiesReferencedHereinAreTheTrademarksAndLogosOfTheirRespectiveOwnersAnyInclusionOfSuchTrademarksOrLogosDoesNotImplyOrConstituteAnyApprovalEndorsementOrSponsorshipOf500GlobalBySuchOwners = styled.span`
	color: rgba(0, 0, 0, 0.65);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Roboto Mono", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 833px;
	position: absolute;
	left: 304px;
	top: 5728px;
`;

const Footer = styled.div`
	height: 732px;
	overflow: hidden;
	background-color: white;
	position: absolute;
	left: 0px;
	top: 6560px;
	right: 0px;
`;

const Frame223 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 64px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + 0px)) - 520px));
	top: 136px;
	width: 1040px;
	height: 536px;
`;

const Frame221 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 121px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Logo64_0001 = styled.div`
	width: 64px;
	height: 64px;
	overflow: hidden;
	position: relative;
`;

const LogoShapeOnly_0001 = styled.div`
	width: 50px;
	height: 50px;
	position: absolute;
	left: 7px;
	top: 7px;
`;

const Union_0001 = styled.img`
	width: 50px;
	height: 50px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Frame220 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: flex-start;
	flex: 1;
	width: 855px;
	box-sizing: border-box;
`;

const Frame201 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 40px;
	box-sizing: border-box;
`;

const Products = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	text-align: left;
`;

const Frame200 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 15px;
	box-sizing: border-box;
`;

const Cloud = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Globalization = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Reflect = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Surf = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Assistant = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Console = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Appbox = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Solutions = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	text-align: left;
`;

const Handoff = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const GetStarted = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const ApiDocs = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Papers = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Games = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Showcase = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Resources = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	text-align: left;
`;

const Docs = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Blogs = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Mockups = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const ClickclickDesign = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Platforms = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	text-align: left;
`;

const Figma = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Sketch = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Xd = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const React_0001 = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Flutter = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Vue = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Svelte = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const HtmlCss = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Unity = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Unreal = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Together = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	text-align: left;
`;

const AboutUs = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const LetSCreateTogether = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const ProejctBy = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Github = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Projects = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const JoinUsOnSlack = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Meetups = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Reddit = styled.span`
	color: rgb(41, 41, 41);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Line34 = styled.div`
	width: 1040px;
	height: 0px;
	border-top: solid 1px rgb(248, 248, 248);
`;

const Frame205 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 12px;
	box-sizing: border-box;
`;

const IconsAntdYoutubeDefault = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const IconsAntdInstagramDefault = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const IconsAntdTwitterOutlined = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const IconsMdiFacebook = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const IconsAntdDribbbleCircleDefault = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const IconsAntdGithubDefault = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Frame248 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	width: 1040px;
	box-sizing: border-box;
`;

const Copyright2021GridaCo = styled.span`
	color: rgb(78, 78, 78);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Frame243 = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 16px;
	box-sizing: border-box;
`;

const Cookies = styled.span`
	color: rgb(78, 78, 78);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
`;

const PrivacyPolicy = styled.span`
	color: rgb(78, 78, 78);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
`;

const TermsAndConditions = styled.span`
	color: rgb(78, 78, 78);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	text-align: left;
`;

const GetHttpsCorsShHttpsInstagramCom = styled.span`
	color: rgba(0, 0, 0, 0.6);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Inter, sans-serif;
	font-weight: 400;
	line-height: 160%;
	text-align: left;
	position: absolute;
	left: 583px;
	top: 1715px;
`;

