import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionPricing>` ('section-pricing')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=15:1613)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=15:1613)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionPricing/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3b4fded0-7047-4710-8959-6fbef3fccb2b)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/15:1613 -->
 */
export function SectionPricing() {
  return (
    <RootWrapperSectionPricing>
      <Pricing>Pricing</Pricing>
      <Group484>
        <Frame497>
          <Frame496>
            <Frame495>
              <ForPersonalProjects>For Personal Projects</ForPersonalProjects>
              <Frame486>
                <_4>$4</_4>
                <Month>/ Month</Month>
              </Frame486>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9a2fc443-2814-434d-b8bb-269544918ff4" />
                <FeatureName>1,000,000 requests per month</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8ba53d22-7889-4fbb-90d1-e509dac62909" />
                <FeatureName>500GB Bandwidth</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/375bd093-a621-4fbb-b1ca-1cb8f4d8f142" />
                <FeatureName>Unlimited Sites</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8f74aa0c-ef80-4e7c-8e75-dc19ea478caa" />
                <FeatureName>Max 6mb per request</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/fa4f525a-d96b-4afc-97d7-aefd4c0a6d60" />
                <FeatureName>Unlimited requests per hour</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/256093de-7356-4ee0-ba9d-68e4d236d908" />
                <FeatureName>No down time</FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>Get started</Label>
          </Button>
        </Frame497>
      </Group484>
      <Group483>
        <Frame497>
          <Frame496>
            <Frame495>
              <ForYourTeam>For your team</ForYourTeam>
              <Frame486_0001>
                <PayAsYouGo>Pay as you go</PayAsYouGo>
                <From10PerMonth>From $10 per month</From10PerMonth>
              </Frame486_0001>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/09e15423-7689-4bec-8040-21c7a6661dba" />
                <FeatureName_0006>
                  1,000,000 requests / month included
                </FeatureName_0006>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/fa245084-337b-4684-8aec-9fb564786e31" />
                <FeatureName>Unlimited traffic</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bef5240e-8cc7-457c-9b6c-7b4d7a9d8c00" />
                <FeatureName_0006>
                  $1 per every next 100,000 requests
                </FeatureName_0006>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3a169bfd-2fff-4288-8ffb-ca09df1d761d" />
                <FeatureName>Unlimited Applications</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/472b55aa-3ac3-43cf-a749-a9ce1327b9b4" />
                <FeatureName>Max 6mb per request</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e8982801-e68e-4f1e-a4d9-db5f13e519b2" />
                <FeatureName>Unlimited requests per hour</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/448e0ac1-6b8c-4f36-873b-89fcae84c7fe" />
                <FeatureName>No down time</FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>Get started</Label>
          </Button>
        </Frame497>
      </Group483>
      <Group485>
        <Frame497>
          <Frame496>
            <Frame495>
              <HobbyTesting>Hobby & Testing</HobbyTesting>
              <Frame486_0001>
                <_4>$0</_4>
              </Frame486_0001>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/72b9c9ac-699c-4a24-b330-107e26602d3c" />
                <FeatureName>10,000 requests per month</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c179610a-49b7-46ba-862c-b12d016dc165" />
                <FeatureName>5GB traffic per month</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bcb384dd-69cb-48e0-9cee-fb60ee9b6bb8" />
                <FeatureName>500 requests per hour</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4267af60-4545-4bcc-8764-d1af0dca937e" />
                <FeatureName>3 Applications</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5735c8b4-aa0a-4364-acf4-d26c5336cca3" />
                <FeatureName>3mb per request</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/516c40cc-dbef-45c2-9cdd-2fa67da73811" />
                <FeatureName>No down time</FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>Get started</Label>
          </Button>
        </Frame497>
      </Group485>
      <FreePricingHeroCardLarge>
        <Frame315>
          <Frame247>
            <Frame246>
              <PricelistFeatureItemFeatured>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4274d736-994a-45df-902c-cce0f898e5f8"
                  alt="icon"
                />
                <FeatureName_0019>1,000,000 requests / month</FeatureName_0019>
              </PricelistFeatureItemFeatured>
              <Component7>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/20ed8c0e-3342-4b13-9326-cf317685e223"
                  alt="icon"
                />
                <FeatureName_0019>5mb per request</FeatureName_0019>
              </Component7>
              <PricelistFeatureItemFeatured>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/615810c9-5071-4ae3-8b76-86e6ab944f90"
                  alt="icon"
                />
                <FeatureName_0019>Unlimited requests per hour</FeatureName_0019>
              </PricelistFeatureItemFeatured>
              <Component7>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7fce7d83-d7ee-41ec-9397-6e4f9c545c39"
                  alt="icon"
                />
                <FeatureName_0019>No down time</FeatureName_0019>
              </Component7>
            </Frame246>
          </Frame247>
          <Frame314>
            <Frame313>
              <Frame244>
                <Free>Free</Free>
                <ForOpenSource>for Open Source</ForOpenSource>
              </Frame244>
              <Frame312>
                <Button_0003>
                  <Label>Apply</Label>
                </Button_0003>
                <LimitedToPublicProjectsThatAreOnGithub>
                  *Limited to Public Projects that are on Github
                </LimitedToPublicProjectsThatAreOnGithub>
              </Frame312>
            </Frame313>
          </Frame314>
        </Frame315>
      </FreePricingHeroCardLarge>
      <Line35 />
      <Frame587>
        <Monthly>Monthly</Monthly>
        <Yearly>Yearly</Yearly>
      </Frame587>
    </RootWrapperSectionPricing>
  );
}

const RootWrapperSectionPricing = styled.div`
  height: 1632px;
  background-color: white;
  position: relative;
`;

const Pricing = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 64px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  line-height: 98%;
  text-align: center;
  position: absolute;
  left: calc((calc((50% + 1px)) - 108px));
  top: 88px;
`;

const Group484 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 10px;
  box-shadow: 0px 4px 128px 32px rgba(0, 0, 0, 0.08);
  border-radius: 8px;
  background-color: white;
  box-sizing: border-box;
  padding: 40px;
  position: absolute;
  left: calc((calc((50% + 0px)) - 190px));
  top: 320px;
  width: 380px;
  height: 673px;
`;

const Frame497 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  flex: 1;
  gap: 142px;
  width: 300px;
  box-sizing: border-box;
`;

const Frame496 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 72px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame495 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 36px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const ForPersonalProjects = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
  align-self: stretch;
  flex-shrink: 0;
`;

const Frame486 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 16px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const _4 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 36px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 500;
  line-height: 135%;
  text-align: left;
`;

const Month = styled.span`
  color: rgba(109, 109, 109, 0.83);
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Frame310 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 16px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const PricelistFeatureItem = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 8px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const IconsMdiCheck = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
`;

const FeatureName = styled.span`
  color: rgb(83, 83, 83);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
  width: 270px;
  flex: 1;
`;

const Button = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  gap: 10px;
  border: solid 1px rgb(28, 28, 28);
  border-radius: 4px;
  align-self: stretch;
  background-color: black;
  box-sizing: border-box;
  padding: 12px 89px;
  flex-shrink: 0;
`;

const Label = styled.span`
  color: white;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  text-align: left;
`;

const Group483 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 24px;
  border: solid 1px rgb(246, 246, 246);
  border-radius: 8px;
  background-color: rgb(252, 252, 252);
  box-sizing: border-box;
  padding: 40px;
  position: absolute;
  left: calc((calc((50% + 406px)) - 190px));
  top: 319px;
  width: 380px;
  height: 713px;
`;

const ForYourTeam = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
  align-self: stretch;
  flex-shrink: 0;
`;

const Frame486_0001 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 16px;
  align-self: stretch;
  height: 49px;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const PayAsYouGo = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 36px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 500;
  line-height: 135%;
  text-align: left;
`;

const From10PerMonth = styled.span`
  color: rgba(109, 109, 109, 0.83);
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
  width: 261px;
`;

const FeatureName_0006 = styled.span`
  color: rgb(83, 83, 83);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
  width: 268px;
  flex: 1;
`;

const Group485 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 24px;
  border: solid 1px rgb(246, 246, 246);
  border-radius: 8px;
  background-color: rgb(252, 252, 252);
  box-sizing: border-box;
  padding: 40px;
  position: absolute;
  left: calc((calc((50% + -406px)) - 190px));
  top: 319px;
  width: 380px;
  height: 673px;
`;

const HobbyTesting = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
  align-self: stretch;
  flex-shrink: 0;
`;

const FreePricingHeroCardLarge = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  box-shadow: 0px 4px 64px 12px rgba(0, 0, 0, 0.08);
  border-radius: 8px;
  background-color: white;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + 1px)) - 520px));
  top: 1184px;
  width: 1040px;
  height: 312px;
`;

const Frame315 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame247 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: flex-start;
  flex: 1;
  gap: 10px;
  border-radius: 8px;
  width: 520px;
  background-color: rgb(252, 252, 252);
  box-sizing: border-box;
  padding: 56px;
`;

const Frame246 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 24px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const PricelistFeatureItemFeatured = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 16px;
  align-self: stretch;
  height: 32px;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame245 = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
`;

const FeatureName_0019 = styled.span`
  color: rgb(94, 94, 94);
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Component7 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 16px;
  align-self: stretch;
  height: 32px;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame314 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  flex: 1;
  gap: 10px;
  width: 520px;
  background-color: white;
  box-sizing: border-box;
  padding: 31px 72px;
`;

const Frame313 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: center;
  flex: none;
  gap: 24px;
  box-sizing: border-box;
`;

const Frame244 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: flex-end;
  flex: none;
  gap: 4px;
  box-sizing: border-box;
`;

const Free = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 42px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  text-align: left;
`;

const ForOpenSource = styled.span`
  color: rgb(99, 99, 99);
  text-overflow: ellipsis;
  font-size: 32px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Frame312 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  flex: none;
  gap: 14px;
  box-sizing: border-box;
`;

const Button_0003 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  flex: none;
  gap: 10px;
  border: solid 1px rgb(28, 28, 28);
  border-radius: 4px;
  width: 337px;
  background-color: black;
  box-sizing: border-box;
  padding: 12px 89px;
`;

const LimitedToPublicProjectsThatAreOnGithub = styled.span`
  color: rgb(154, 154, 154);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
`;

const Line35 = styled.div`
  width: 1039px;
  height: 0px;
  border-top: solid 1px rgba(0, 0, 0, 0.1);
  position: absolute;
  left: calc((calc((50% + 1px)) - 520px));
  top: 1108px;
`;

const Frame587 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 12px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + 0px)) - 52px));
  top: 229px;
  width: 104px;
  height: 14px;
`;

const Monthly = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 14px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  line-height: 98%;
  text-align: left;
`;

const Yearly = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 14px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 98%;
  text-align: left;
`;
