import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionHero>` ('section-hero')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=15:1784)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=15:1784)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionHero/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c745a7fe-1f00-4cbf-841e-b830c523bcbe)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/15:1784 -->
 */
export function SectionHero() {
  return (
    <RootWrapperSectionHero>
      <Frame577>
        <SickOfCorsErrors>
          Sick of<br/>
cors errors?
        </SickOfCorsErrors>
        <AFastReliableCorsProxyForYourWebsites>
          A Fast & Reliable CORS Proxy for your websites
        </AFastReliableCorsProxyForYourWebsites>
      </Frame577>
      <Frame555>
        <Frame549>
          <HttpsExampleCom>
            https://example.com
          </HttpsExampleCom>
        </Frame549>
        <Frame550>
          <Frame551>
            <Frame556>
              <Get>
                GET
              </Get>
            </Frame556>
            <Frame30>
              <Line6/>
              <IconsMdiArrowDropDown src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/22b7e99a-5d10-4957-a864-604a3c8f3d04" />
            </Frame30>
          </Frame551>
        </Frame550>
      </Frame555>
      <Frame570>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8733db9d-8121-4e92-8093-7d4a76e95ab3" alt="icon"/>
          <Secure>
            Secure
          </Secure>
        </Frame562>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/55a5f9cb-85ee-4cdb-a3ba-4a7de24d63cd" alt="icon"/>
          <Reliable>
            Reliable
          </Reliable>
        </Frame562>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/fb29bca8-0eb0-470d-9aea-12a65da2d6c6" alt="icon"/>
          <Fast>
            Fast
          </Fast>
        </Frame562>
        <Frame562>
          <Frame561 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/13f703aa-e0eb-425e-b5fe-d46bc5bdb1f5" alt="icon"/>
          <ACorsAnywhereMirror>
            A cors-anywhere mirror
          </ACorsAnywhereMirror>
        </Frame562>
      </Frame570>
      <Frame578>
        <Frame575>
          <Frame574 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3d897fcd-8091-4fc4-8794-1f5694ea66f8" alt="icon"/>
        </Frame575>
        <AccessToFetchAtHttpsTargetDomainFromOriginHttpsMySiteHasBeenBlockedByCorsPolicyNoAccessControlAllowOriginHeaderIsPresentOnTheRequestedResourceIfAnOpaqueResponseServesYourNeedsSetTheRequestSModeToNoCorsToFetchTheResourceWithCorsDisabled>
          Access to fetch at ‘https://target.domain’ from origin ‘https://my.site’ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on the requested resource. If an opaque response serves your needs, set the request’s mode to ‘no-cors’ to fetch the resource with CORS disabled.
        </AccessToFetchAtHttpsTargetDomainFromOriginHttpsMySiteHasBeenBlockedByCorsPolicyNoAccessControlAllowOriginHeaderIsPresentOnTheRequestedResourceIfAnOpaqueResponseServesYourNeedsSetTheRequestSModeToNoCorsToFetchTheResourceWithCorsDisabled>
      </Frame578>
    </RootWrapperSectionHero>
  )
}

const RootWrapperSectionHero = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Frame577 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 32px;
	box-sizing: border-box;
	position: absolute;
	left: 200px;
	top: 171px;
	width: 551px;
	height: 256px;
`;

const SickOfCorsErrors = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 80px;
	font-family: Inter, sans-serif;
	font-weight: 700;
	letter-spacing: -2px;
	line-height: 98%;
	text-align: left;
	width: 553px;
`;

const AFastReliableCorsProxyForYourWebsites = styled.span`
	color: rgba(0, 0, 0, 0.6);
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: Inter, sans-serif;
	font-weight: 500;
	line-height: 160%;
	text-align: left;
	width: 356px;
`;

const Frame555 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 14px;
	box-sizing: border-box;
	position: absolute;
	left: 200px;
	top: 517px;
	width: 673px;
	height: 66px;
`;

const Frame549 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 4px 48px  rgba(0, 0, 0, 0.12);
	border: solid 1px rgb(210, 210, 210);
	border-radius: 4px;
	width: 508px;
	background-color: white;
	box-sizing: border-box;
	padding: 24px;
`;

const HttpsExampleCom = styled.span`
	color: rgb(181, 181, 181);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

const Frame550 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 4px 48px  rgba(0, 0, 0, 0.12);
	border: solid 1px rgb(210, 210, 210);
	border-radius: 4px;
	width: 151px;
	height: 66px;
	background-color: black;
	box-sizing: border-box;
	padding-left: 12px;
	padding-right: 4px;
`;

const Frame551 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 8px;
	align-self: stretch;
	height: 66px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame556 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 10px;
	align-self: stretch;
	width: 99px;
	box-sizing: border-box;
	padding: 10px;
	flex-shrink: 0;
`;

const Get = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

const Frame30 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 4px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Line6 = styled.div`
	width: 66px;
	border-top: solid 1px rgba(255, 255, 255, 0.37);
	align-self: stretch;
	flex-shrink: 0;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const IconsMdiArrowDropDown = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Frame570 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 138px;
	box-sizing: border-box;
	position: absolute;
	left: 200px;
	top: 703px;
	width: 956px;
	height: 24px;
`;

const Frame562 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 15px;
	box-sizing: border-box;
`;

const Frame561 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Secure = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Reliable = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Fast = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const ACorsAnywhereMirror = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Monaco, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Frame578 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 10px;
	box-shadow: 0px 4px 32px  rgba(255, 0, 0, 0.08);
	border: solid 1px rgb(255, 46, 46);
	border-radius: 4px;
	background-color: rgb(252, 240, 240);
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: calc((calc((50% + 351px)) - 245px));
	top: 197px;
	width: 490px;
	height: 167px;
`;

const Frame575 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-sizing: border-box;
	padding: 4px 0px 0px;
`;

const Frame574 = styled.img`
	width: 15px;
	height: 15px;
	object-fit: cover;
`;

const AccessToFetchAtHttpsTargetDomainFromOriginHttpsMySiteHasBeenBlockedByCorsPolicyNoAccessControlAllowOriginHeaderIsPresentOnTheRequestedResourceIfAnOpaqueResponseServesYourNeedsSetTheRequestSModeToNoCorsToFetchTheResourceWithCorsDisabled = styled.span`
	color: rgb(233, 22, 6);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Source Code Pro", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 119%;
	text-align: left;
	width: 445px;
	flex: 1;
`;

