import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionCtaLast>` ('section-cta-last')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=15:1600)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=15:1600)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionCtaLast/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9f8bb5c4-af20-4f88-86de-1641944601f4)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/15:1600 -->
 */
export function SectionCtaLast() {
  return (
    <RootWrapperSectionCtaLast>
      <Frame270>
        <SayByeToCorsErrors>
          Say bye to cors errors
        </SayByeToCorsErrors>
        <AndFocusOnYouReDevelopment>
          And focus on you’re development
        </AndFocusOnYouReDevelopment>
      </Frame270>
      <ScribbleGuide>
        <WeLlSendYouAApiKeyToGetStarted>
          We’ll send you a Api key to get started
        </WeLlSendYouAApiKeyToGetStarted>
        <PointerArtwork src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/25a24762-ffd0-4e6d-8c6c-7b3682aefe07" alt="image of PointerArtwork"/>
      </ScribbleGuide>
      <Frame572>
        <Frame549>
          <EnterYourEmailAddress>
            Enter your email address
          </EnterYourEmailAddress>
        </Frame549>
        <Frame550>
          <Frame556>
            <SendMeAnApiKey>
              Send me an API Key
            </SendMeAnApiKey>
          </Frame556>
        </Frame550>
      </Frame572>
    </RootWrapperSectionCtaLast>
  )
}

const RootWrapperSectionCtaLast = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Frame270 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 36px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + -1px)) - 337px));
	top: 105px;
	width: 673px;
	height: 137px;
`;

const SayByeToCorsErrors = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 64px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 700;
	line-height: 98%;
	text-align: center;
`;

const AndFocusOnYouReDevelopment = styled.span`
	color: rgb(68, 69, 69);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	line-height: 160%;
	text-align: center;
	align-self: stretch;
	flex-shrink: 0;
`;

const ScribbleGuide = styled.div`
	width: 217px;
	height: 112px;
	position: absolute;
	left: 235px;
	top: 302px;
`;

const WeLlSendYouAApiKeyToGetStarted = styled.span`
	color: rgb(164, 164, 164);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: "Nanum Pen Script", sans-serif;
	font-weight: 400;
	line-height: 98%;
	text-align: left;
	width: 213px;
	position: absolute;
	left: calc((calc((50% + -2px)) - 107px));
	top: 25px;
	transform: rotate(-7deg);
	transform-origin: top left;
`;

const PointerArtwork = styled.img`
	width: 53px;
	height: 69px;
	object-fit: cover;
	position: absolute;
	left: calc((calc((50% + 59px)) - 26px));
	top: 49px;
	transform: rotate(-23deg);
	transform-origin: top left;
`;

const Frame572 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 14px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + -1px)) - 373px));
	top: 414px;
	width: 745px;
	height: 66px;
`;

const Frame549 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 4px 48px  rgba(0, 0, 0, 0.12);
	border: solid 1px rgb(210, 210, 210);
	border-radius: 4px;
	width: 508px;
	background-color: white;
	box-sizing: border-box;
	padding: 24px;
`;

const EnterYourEmailAddress = styled.span`
	color: rgb(181, 181, 181);
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 400;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

const Frame550 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 4px 48px  rgba(0, 0, 0, 0.12);
	border: solid 1px rgb(210, 210, 210);
	border-radius: 4px;
	height: 66px;
	background-color: black;
	box-sizing: border-box;
	padding: 0px 21px;
`;

const Frame556 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	height: 66px;
	box-sizing: border-box;
	padding: 10px;
	flex-shrink: 0;
`;

const SendMeAnApiKey = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Helvetica Neue", sans-serif;
	font-weight: 500;
	letter-spacing: -1px;
	line-height: 98%;
	text-align: left;
`;

