import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionHero>` ('section-hero')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=15:1784)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=15:1784)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionHero/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9ad3b248-98c3-46dc-9668-e4bee71c948d)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/15:1784 -->
 */
export function SectionHero() {
  return (
    <RootWrapperSectionHero>
      <Headings>
        <HeadingAsH1>
          Sick of
          <br />
          cors errors?
        </HeadingAsH1>
        <DescriptionAsP>
          A Fast & Reliable CORS Proxy for your websites
        </DescriptionAsP>
      </Headings>
      <Cta>
        <RequestInputAsInput type="text" placeholder="https://example.com" />
        <Button>
          <ButtonContents>
            <Type>
              <Label>GET</Label>
            </Type>
            <Menu>
              <Line />
              <IconsMdiArrowDropDown src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1021432c-7395-465c-a0c6-26b80afe3821" />
            </Menu>
          </ButtonContents>
        </Button>
      </Cta>
      <FeatuersList>
        <Item>
          <Icon
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/23d868b3-ada2-47ab-b644-9c74e28b62f7"
            alt="icon"
          />
          <ItemText>Secure</ItemText>
        </Item>
        <Item>
          <Icon
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/21bda769-3c84-4886-be5c-9f90bbba4169"
            alt="icon"
          />
          <ItemText>Reliable</ItemText>
        </Item>
        <Item>
          <Icon
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/eae41a02-31cc-48aa-af9a-53f757479aec"
            alt="icon"
          />
          <ItemText>Fast</ItemText>
        </Item>
        <Item>
          <Icon
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/96c24982-f0ff-4c94-b19b-962b0ff748ef"
            alt="icon"
          />
          <ItemText>A cors-anywhere mirror</ItemText>
        </Item>
      </FeatuersList>
      <Example>
        <X>
          <Frame574
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2bb4e088-bfe5-422f-a778-1cc2fed4522f"
            alt="icon"
          />
        </X>
        <Text>
          Access to XMLHttpRequest at ‘https://target.domain’ from origin
          ‘https://my.site’ has been blocked by CORS policy: No
          ‘Access-Control-Allow-Origin’ header is present on the requested
          resource.
        </Text>
      </Example>
      <FixThisInMinutes>Fix this in minutes</FixThisInMinutes>
      <PointerArtwork
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/cefd949e-6c52-4e71-ac3a-32dd94f79030"
        alt="image of PointerArtwork"
      />
    </RootWrapperSectionHero>
  );
}

const RootWrapperSectionHero = styled.div`
  min-height: 100vh;
  background-color: white;
  position: relative;
`;

const Headings = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 32px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + -245px)) - 276px));
  top: 171px;
  width: 551px;
  height: 256px;
`;

const HeadingAsH1 = styled.h1`
  color: black;
  text-overflow: ellipsis;
  font-size: 80px;
  font-family: Inter, sans-serif;
  font-weight: 700;
  letter-spacing: -2px;
  line-height: 98%;
  text-align: left;
`;

const DescriptionAsP = styled.p`
  color: rgba(0, 0, 0, 0.6);
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: Inter, sans-serif;
  font-weight: 500;
  line-height: 160%;
  text-align: left;
`;

const Cta = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 14px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + -184px)) - 337px));
  top: 517px;
  width: 673px;
  height: 66px;
`;

const RequestInputAsInput = styled.input`
  width: 508px;
  box-shadow: 0px 4px 48px rgba(0, 0, 0, 0.12);
  background-color: white;
  border: solid 1px rgb(210, 210, 210);
  border-radius: 4px;
  padding: 24px;
  box-sizing: border-box;
  color: rgb(181, 181, 181);
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  letter-spacing: -1px;
  line-height: 98%;
  text-align: start;

  ::placeholder {
    color: rgb(181, 181, 181);
    font-size: 18px;
    font-family: "Helvetica Neue", sans-serif;
    font-weight: 400;
  }
`;

const Button = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  flex: none;
  gap: 10px;
  box-shadow: 0px 4px 48px rgba(0, 0, 0, 0.12);
  border: solid 1px rgb(210, 210, 210);
  border-radius: 4px;
  width: 151px;
  height: 66px;
  background-color: black;
  box-sizing: border-box;
  padding-left: 12px;
  padding-right: 4px;
`;

const ButtonContents = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  flex: 1;
  gap: 8px;
  align-self: stretch;
  height: 66px;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Type = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  flex: 1;
  gap: 10px;
  align-self: stretch;
  width: 99px;
  box-sizing: border-box;
  padding: 10px;
  flex-shrink: 0;
`;

const Label = styled.span`
  color: white;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 500;
  letter-spacing: -1px;
  line-height: 98%;
  text-align: left;
`;

const Menu = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  gap: 4px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Line = styled.div`
  width: 66px;
  border-top: solid 1px rgba(255, 255, 255, 0.37);
  align-self: stretch;
  flex-shrink: 0;
  transform: rotate(-270deg);
  transform-origin: top left;
`;

const IconsMdiArrowDropDown = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
`;

const FeatuersList = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 138px;
  box-sizing: border-box;
  position: absolute;
  left: calc((calc((50% + -42px)) - 478px));
  top: 703px;
  width: 956px;
  height: 24px;
`;

const Item = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  flex: none;
  gap: 15px;
  box-sizing: border-box;
`;

const Icon = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
`;

const ItemText = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: Monaco, sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Example = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 10px;
  box-shadow: 0px 4px 32px rgba(255, 0, 0, 0.08);
  border: solid 1px rgb(255, 46, 46);
  border-radius: 4px;
  background-color: rgb(252, 240, 240);
  box-sizing: border-box;
  padding: 10px;
  position: absolute;
  left: calc((calc((50% + 375px)) - 269px));
  top: 247px;
  width: 537px;
  height: 104px;
`;

const X = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  flex: none;
  gap: 10px;
  box-sizing: border-box;
  padding: 4px 0px 0px;
`;

const Frame574 = styled.img`
  width: 15px;
  height: 15px;
  object-fit: cover;
`;

const Text = styled.span`
  color: rgb(233, 22, 6);
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Source Code Pro", sans-serif;
  font-weight: 500;
  letter-spacing: -1px;
  line-height: 119%;
  text-align: left;
  width: 492px;
  flex: 1;
`;

const FixThisInMinutes = styled.span`
  color: rgb(164, 164, 164);
  text-overflow: ellipsis;
  font-size: 24px;
  font-family: "Nanum Pen Script", sans-serif;
  font-weight: 400;
  line-height: 98%;
  text-align: left;
  position: absolute;
  left: calc((calc((50% + 102px)) - 84px));
  top: 123px;
  transform: rotate(-7deg);
  transform-origin: top left;
`;

const PointerArtwork = styled.img`
  width: 53px;
  height: 69px;
  object-fit: cover;
  position: absolute;
  left: calc((calc((50% + 148px)) - 26px));
  top: 143px;
  transform: rotate(-9deg);
  transform-origin: top left;
`;
