import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionDisclaimer>` ('section-disclaimer')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=15:1597)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=15:1597)
 * 
 * 
 * ---
 * @example
 * ```tsx
 * import React from "react";
 * 
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionDisclaimer/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/70ee1cc4-4a27-4ad3-883c-89ca5ff7d1e0)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 * 
 * 
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/15:1597 -->
 */
export function SectionDisclaimer() {
  return (
    <RootWrapperSectionDisclaimer>
      <Disclaimer>
        DISCLAIMER
      </Disclaimer>
      <_1CorsShIsAMirrorServicesForTheOriginalProjectCorsAnywhereByRobWBothProjectIsLicensedUnderMitAsOfSeptember20222RevenueSharingTheRevenueByCorsShWillBeDistributedBackToOriginalAuthors3AsOf31March2022IncludesLocationOfEmployeesContractorsAndConsultants4AsOf31March2022AllFiguresAreBasedOnInternalDataAndThirdPartyDataWhichMayNotHaveBeenExternallyVerifiedPortfolioCompaniesDisplayedOnThisPageAreNotNecessarilyRepresentativeOfAllInvestmentsInVehiclesManagedBy500StartupsManagementCompanyLlcTogetherWithItsAffiliates500GlobalAndThereCanBeNoAssuranceThatTheInvestmentsWillBeProfitableOrThatOtherInvestmentsMadeInTheFutureWillHaveSimilarCharacteristicsOrResultsThisListIncludesCurrentAndFormer500GlobalPortfolioCompaniesWhichHaveBeenAcquiredAsWellAsCompaniesWhichHaveUndergoneAnInitialPublicOfferingThisListIsUpdatedPeriodicallyAndAsSuchMayNotReflectRecent500GlobalInvestmentsPastResultsOf500GlobalInvestmentsPooledInvestmentVehiclesOrInvestmentStrategiesAreNotNecessarilyIndicativeOfFutureResultsNoContentOnThisPageShouldBeConsideredAsAnOfferToSellOrSolicitationOfInterestToPurchaseAnySecuritiesConstructedAsFundMarketingMaterialsByProspectiveInvestorsConsideringAnInvestmentIntoAny500GlobalFundOrUsedAsTheBasisForAnyInvestmentDecisionsAllLogosNamesAndTrademarksOfThirdPartiesReferencedHereinAreTheTrademarksAndLogosOfTheirRespectiveOwnersAnyInclusionOfSuchTrademarksOrLogosDoesNotImplyOrConstituteAnyApprovalEndorsementOrSponsorshipOf500GlobalBySuchOwners>
        1. CORS.SH is a mirror services for the original project cors-anywhere by Rob--W. Both project is licensed under MIT as of September 2022.<br/>
<br/>
2. Revenue sharing. The revenue by cors.sh will be distributed back to original authors<br/>
<br/>
3. AS OF 31 MARCH 2022. INCLUDES LOCATION OF EMPLOYEES, CONTRACTORS AND CONSULTANTS.<br/>
<br/>
4. AS OF 31 MARCH 2022. ALL FIGURES ARE BASED ON INTERNAL DATA AND THIRD PARTY DATA WHICH MAY NOT HAVE BEEN EXTERNALLY VERIFIED. PORTFOLIO COMPANIES DISPLAYED ON THIS PAGE ARE NOT NECESSARILY REPRESENTATIVE OF ALL INVESTMENTS IN VEHICLES MANAGED BY 500 STARTUPS MANAGEMENT COMPANY, L.L.C. (TOGETHER WITH ITS AFFILIATES, “500 GLOBAL”) AND THERE CAN BE NO ASSURANCE THAT THE INVESTMENTS WILL BE PROFITABLE OR THAT OTHER INVESTMENTS MADE IN THE FUTURE WILL HAVE SIMILAR CHARACTERISTICS OR RESULTS. THIS LIST INCLUDES CURRENT AND FORMER 500 GLOBAL PORTFOLIO COMPANIES WHICH HAVE BEEN ACQUIRED AS WELL AS COMPANIES WHICH HAVE UNDERGONE AN INITIAL PUBLIC OFFERING. THIS LIST IS UPDATED PERIODICALLY AND AS SUCH MAY NOT REFLECT RECENT 500 GLOBAL INVESTMENTS. PAST RESULTS OF 500 GLOBAL INVESTMENTS, POOLED INVESTMENT VEHICLES, OR INVESTMENT STRATEGIES ARE NOT NECESSARILY INDICATIVE OF FUTURE RESULTS. NO CONTENT ON THIS PAGE SHOULD BE CONSIDERED AS AN OFFER TO SELL OR SOLICITATION OF INTEREST TO PURCHASE ANY SECURITIES, CONSTRUCTED AS FUND MARKETING MATERIALS BY PROSPECTIVE INVESTORS CONSIDERING AN INVESTMENT INTO ANY 500 GLOBAL FUND, OR USED AS THE BASIS FOR ANY INVESTMENT DECISIONS. ALL LOGOS, NAMES, AND TRADEMARKS OF THIRD PARTIES REFERENCED HEREIN ARE THE TRADEMARKS AND LOGOS OF THEIR RESPECTIVE OWNERS. ANY INCLUSION OF SUCH TRADEMARKS OR LOGOS DOES NOT IMPLY OR CONSTITUTE ANY APPROVAL, ENDORSEMENT OR SPONSORSHIP OF 500 GLOBAL BY SUCH OWNERS.
      </_1CorsShIsAMirrorServicesForTheOriginalProjectCorsAnywhereByRobWBothProjectIsLicensedUnderMitAsOfSeptember20222RevenueSharingTheRevenueByCorsShWillBeDistributedBackToOriginalAuthors3AsOf31March2022IncludesLocationOfEmployeesContractorsAndConsultants4AsOf31March2022AllFiguresAreBasedOnInternalDataAndThirdPartyDataWhichMayNotHaveBeenExternallyVerifiedPortfolioCompaniesDisplayedOnThisPageAreNotNecessarilyRepresentativeOfAllInvestmentsInVehiclesManagedBy500StartupsManagementCompanyLlcTogetherWithItsAffiliates500GlobalAndThereCanBeNoAssuranceThatTheInvestmentsWillBeProfitableOrThatOtherInvestmentsMadeInTheFutureWillHaveSimilarCharacteristicsOrResultsThisListIncludesCurrentAndFormer500GlobalPortfolioCompaniesWhichHaveBeenAcquiredAsWellAsCompaniesWhichHaveUndergoneAnInitialPublicOfferingThisListIsUpdatedPeriodicallyAndAsSuchMayNotReflectRecent500GlobalInvestmentsPastResultsOf500GlobalInvestmentsPooledInvestmentVehiclesOrInvestmentStrategiesAreNotNecessarilyIndicativeOfFutureResultsNoContentOnThisPageShouldBeConsideredAsAnOfferToSellOrSolicitationOfInterestToPurchaseAnySecuritiesConstructedAsFundMarketingMaterialsByProspectiveInvestorsConsideringAnInvestmentIntoAny500GlobalFundOrUsedAsTheBasisForAnyInvestmentDecisionsAllLogosNamesAndTrademarksOfThirdPartiesReferencedHereinAreTheTrademarksAndLogosOfTheirRespectiveOwnersAnyInclusionOfSuchTrademarksOrLogosDoesNotImplyOrConstituteAnyApprovalEndorsementOrSponsorshipOf500GlobalBySuchOwners>
    </RootWrapperSectionDisclaimer>
  )
}

const RootWrapperSectionDisclaimer = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Disclaimer = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: "Roboto Mono", sans-serif;
	font-weight: 500;
	text-align: center;
	position: absolute;
	left: calc((calc((50% + 1px)) - 55px));
	top: 161px;
`;

const _1CorsShIsAMirrorServicesForTheOriginalProjectCorsAnywhereByRobWBothProjectIsLicensedUnderMitAsOfSeptember20222RevenueSharingTheRevenueByCorsShWillBeDistributedBackToOriginalAuthors3AsOf31March2022IncludesLocationOfEmployeesContractorsAndConsultants4AsOf31March2022AllFiguresAreBasedOnInternalDataAndThirdPartyDataWhichMayNotHaveBeenExternallyVerifiedPortfolioCompaniesDisplayedOnThisPageAreNotNecessarilyRepresentativeOfAllInvestmentsInVehiclesManagedBy500StartupsManagementCompanyLlcTogetherWithItsAffiliates500GlobalAndThereCanBeNoAssuranceThatTheInvestmentsWillBeProfitableOrThatOtherInvestmentsMadeInTheFutureWillHaveSimilarCharacteristicsOrResultsThisListIncludesCurrentAndFormer500GlobalPortfolioCompaniesWhichHaveBeenAcquiredAsWellAsCompaniesWhichHaveUndergoneAnInitialPublicOfferingThisListIsUpdatedPeriodicallyAndAsSuchMayNotReflectRecent500GlobalInvestmentsPastResultsOf500GlobalInvestmentsPooledInvestmentVehiclesOrInvestmentStrategiesAreNotNecessarilyIndicativeOfFutureResultsNoContentOnThisPageShouldBeConsideredAsAnOfferToSellOrSolicitationOfInterestToPurchaseAnySecuritiesConstructedAsFundMarketingMaterialsByProspectiveInvestorsConsideringAnInvestmentIntoAny500GlobalFundOrUsedAsTheBasisForAnyInvestmentDecisionsAllLogosNamesAndTrademarksOfThirdPartiesReferencedHereinAreTheTrademarksAndLogosOfTheirRespectiveOwnersAnyInclusionOfSuchTrademarksOrLogosDoesNotImplyOrConstituteAnyApprovalEndorsementOrSponsorshipOf500GlobalBySuchOwners = styled.span`
	color: rgba(0, 0, 0, 0.65);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Roboto Mono", sans-serif;
	font-weight: 400;
	text-align: left;
	width: 833px;
	position: absolute;
	left: calc((calc((50% + 1px)) - 417px));
	top: 245px;
`;

