import React from "react";
import styled from "@emotion/styled";
/**
 * `<SectionPricing>` ('section-pricing')
 * - [Open in Figma](https://figma.com/file/aPfdtNb1aGFIN9p05cmmVY?node-id=15:1613)
 * - [Open in Grida](https://code.grida.co/files/aPfdtNb1aGFIN9p05cmmVY?node=15:1613)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SectionPricing/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c919ecf4-0b2d-472a-b182-632cda7eebb6)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://aPfdtNb1aGFIN9p05cmmVY/15:1613 -->
 */
export function SectionPricing() {
  return (
    <RootWrapperSectionPricing id="pricing">
      <Pricing>Pricing</Pricing>
      <Group484>
        <Frame497>
          <Frame496>
            <Frame495>
              <ForPersonalProjects>For Personal Projects</ForPersonalProjects>
              <Frame486>
                <_4>$4</_4>
                <Month>/ Month</Month>
              </Frame486>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5b95ce4c-8416-4293-b27b-0894b8eeb38d" />
                <FeatureName>1,000,000 requests per month</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6da6dbac-c995-419d-833b-4fc39e6fc08b" />
                <FeatureName>500GB Bandwidth</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/879ddd76-d87a-4ec2-a72d-b88622ca7f47" />
                <FeatureName>Unlimited Sites</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/466b54f4-ff3b-4ebb-99cf-5919977e16de" />
                <FeatureName>Max 6mb per request</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/25609e20-baff-40f7-bc79-e23c3a638713" />
                <FeatureName>Unlimited requests per hour</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b0527060-6b6f-4d6d-99fd-3928c2849a9e" />
                <FeatureName>No down time</FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>Get started</Label>
          </Button>
        </Frame497>
      </Group484>
      <Group483>
        <Frame497>
          <Frame496>
            <Frame495>
              <ForYourTeam>For your team</ForYourTeam>
              <Frame486_0001>
                <PayAsYouGo>Pay as you go</PayAsYouGo>
                <From10PerMonth>From $10 per month</From10PerMonth>
              </Frame486_0001>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/88fbca8c-0bcb-4d5e-be7c-46901efdfebb" />
                <FeatureName_0006>
                  1,000,000 requests / month included
                </FeatureName_0006>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/af9acf26-bff9-4c81-b2c3-54b38d1b26bb" />
                <FeatureName>Unlimited traffic</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1f52620d-c7e9-489b-bff0-df220194d2d2" />
                <FeatureName_0006>
                  $1 per every next 100,000 requests
                </FeatureName_0006>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/013a0725-eebc-434f-ae64-1d7721e84aa0" />
                <FeatureName>Unlimited Applications</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8baf41ba-01f8-4f81-8197-570f05bbc7a8" />
                <FeatureName>Max 6mb per request</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e19e37b3-02a9-4d50-bd3e-6c74017b6255" />
                <FeatureName>Unlimited requests per hour</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b73dbc6e-bfd8-45c1-b440-e84e910b2b8c" />
                <FeatureName>No down time</FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>Get started</Label>
          </Button>
        </Frame497>
      </Group483>
      <Group485>
        <Frame497>
          <Frame496>
            <Frame495>
              <HobbyTesting>Hobby & Testing</HobbyTesting>
              <Frame486_0001>
                <_4>$0</_4>
              </Frame486_0001>
            </Frame495>
            <Frame310>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b5b73403-2c31-4777-83bf-0ca0694cc47a" />
                <FeatureName>10,000 requests per month</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2be675fe-c7e0-4de5-87d0-b20346aa0d1c" />
                <FeatureName>5GB traffic per month</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7fad6f28-b405-4b0f-afe7-5584f36b82c6" />
                <FeatureName>500 requests per hour</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4154f0b3-4e9d-46e6-ad43-73ccaa991f2e" />
                <FeatureName>3 Applications</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9fcc703e-5a44-4947-8dbd-1d98b924e0d5" />
                <FeatureName>3mb per request</FeatureName>
              </PricelistFeatureItem>
              <PricelistFeatureItem>
                <IconsMdiCheck src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/546457c9-454f-4334-9b60-d7f8ef740491" />
                <FeatureName>No down time</FeatureName>
              </PricelistFeatureItem>
            </Frame310>
          </Frame496>
          <Button>
            <Label>Get started</Label>
          </Button>
        </Frame497>
      </Group485>
      <FreePricingHeroCardLarge>
        <Frame315>
          <Frame247>
            <Frame246>
              <PricelistFeatureItemFeatured>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0d3afb1b-f596-4387-b428-25ae569f192b"
                  alt="icon"
                />
                <FeatureName_0019>1,000,000 requests / month</FeatureName_0019>
              </PricelistFeatureItemFeatured>
              <Component7>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8713ab82-1a06-4a53-bc0e-ac05ba836a4d"
                  alt="icon"
                />
                <FeatureName_0019>5mb per request</FeatureName_0019>
              </Component7>
              <PricelistFeatureItemFeatured>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b68ffa66-534c-4f6e-878e-36bcbe073050"
                  alt="icon"
                />
                <FeatureName_0019>Unlimited requests per hour</FeatureName_0019>
              </PricelistFeatureItemFeatured>
              <Component7>
                <Frame245
                  src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/aad8b191-ea1a-424d-9f41-0efe9f94d434"
                  alt="icon"
                />
                <FeatureName_0019>No down time</FeatureName_0019>
              </Component7>
            </Frame246>
          </Frame247>
          <Frame314>
            <Frame313>
              <Frame244>
                <Free>Free</Free>
                <ForOpenSource>for Open Source</ForOpenSource>
              </Frame244>
              <Frame312>
                <Button_0003>
                  <Label>Apply</Label>
                </Button_0003>
                <LimitedToPublicProjectsThatAreOnGithub>
                  *Limited to Public Projects that are on Github
                </LimitedToPublicProjectsThatAreOnGithub>
              </Frame312>
            </Frame313>
          </Frame314>
        </Frame315>
      </FreePricingHeroCardLarge>
      <Line35 />
    </RootWrapperSectionPricing>
  );
}

const RootWrapperSectionPricing = styled.div`
  min-height: 100vh;
  background-color: white;
  position: relative;
`;

const Pricing = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 64px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  line-height: 98%;
  text-align: center;
  position: absolute;
  left: calc((calc((50% + 1px)) - 108px));
  top: 58px;
`;

const Group484 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 10px;
  box-shadow: 0px 4px 128px 32px rgba(0, 0, 0, 0.08);
  border-radius: 8px;
  background-color: white;
  box-sizing: border-box;
  padding: 40px;
  position: absolute;
  left: 530px;
  top: 230px;
  width: 380px;
  height: 673px;
`;

const Frame497 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  flex: 1;
  gap: 142px;
  width: 300px;
  box-sizing: border-box;
`;

const Frame496 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 72px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame495 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 36px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const ForPersonalProjects = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
  align-self: stretch;
  flex-shrink: 0;
`;

const Frame486 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 16px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const _4 = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 36px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 500;
  line-height: 135%;
  text-align: left;
`;

const Month = styled.span`
  color: rgba(109, 109, 109, 0.83);
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Frame310 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 16px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const PricelistFeatureItem = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 8px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const IconsMdiCheck = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
`;

const FeatureName = styled.span`
  color: rgb(83, 83, 83);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
  width: 270px;
  flex: 1;
`;

const Button = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  gap: 10px;
  border: solid 1px rgb(28, 28, 28);
  border-radius: 4px;
  align-self: stretch;
  background-color: black;
  box-sizing: border-box;
  padding: 12px 89px;
  flex-shrink: 0;
`;

const Label = styled.span`
  color: white;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  text-align: left;
`;

const Group483 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 24px;
  border: solid 1px rgb(246, 246, 246);
  border-radius: 8px;
  background-color: rgb(252, 252, 252);
  box-sizing: border-box;
  padding: 40px;
  position: absolute;
  left: 936px;
  top: 229px;
  width: 380px;
  height: 713px;
`;

const ForYourTeam = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
  align-self: stretch;
  flex-shrink: 0;
`;

const Frame486_0001 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 16px;
  align-self: stretch;
  height: 49px;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const PayAsYouGo = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 36px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 500;
  line-height: 135%;
  text-align: left;
`;

const From10PerMonth = styled.span`
  color: rgba(109, 109, 109, 0.83);
  text-overflow: ellipsis;
  font-size: 21px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
  width: 261px;
`;

const FeatureName_0006 = styled.span`
  color: rgb(83, 83, 83);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
  width: 268px;
  flex: 1;
`;

const Group485 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: flex-start;
  gap: 24px;
  border: solid 1px rgb(246, 246, 246);
  border-radius: 8px;
  background-color: rgb(252, 252, 252);
  box-sizing: border-box;
  padding: 40px;
  position: absolute;
  left: 124px;
  top: 229px;
  width: 380px;
  height: 673px;
`;

const HobbyTesting = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
  align-self: stretch;
  flex-shrink: 0;
`;

const FreePricingHeroCardLarge = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  box-shadow: 0px 4px 64px 12px rgba(0, 0, 0, 0.08);
  border-radius: 8px;
  background-color: white;
  box-sizing: border-box;
  position: absolute;
  left: 201px;
  top: 1094px;
  width: 1040px;
  height: 312px;
`;

const Frame315 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame247 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: flex-start;
  flex: 1;
  gap: 10px;
  border-radius: 8px;
  width: 520px;
  background-color: rgb(252, 252, 252);
  box-sizing: border-box;
  padding: 56px;
`;

const Frame246 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: flex-start;
  gap: 24px;
  align-self: stretch;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const PricelistFeatureItemFeatured = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 16px;
  align-self: stretch;
  height: 32px;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame245 = styled.img`
  width: 24px;
  height: 24px;
  object-fit: cover;
`;

const FeatureName_0019 = styled.span`
  color: rgb(94, 94, 94);
  text-overflow: ellipsis;
  font-size: 18px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Component7 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: row;
  align-items: center;
  gap: 16px;
  align-self: stretch;
  height: 32px;
  box-sizing: border-box;
  flex-shrink: 0;
`;

const Frame314 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  flex: 1;
  gap: 10px;
  width: 520px;
  background-color: white;
  box-sizing: border-box;
  padding: 31px 72px;
`;

const Frame313 = styled.div`
  display: flex;
  justify-content: flex-start;
  flex-direction: column;
  align-items: center;
  flex: none;
  gap: 24px;
  box-sizing: border-box;
`;

const Frame244 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: flex-end;
  flex: none;
  gap: 4px;
  box-sizing: border-box;
`;

const Free = styled.span`
  color: black;
  text-overflow: ellipsis;
  font-size: 42px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 700;
  text-align: left;
`;

const ForOpenSource = styled.span`
  color: rgb(99, 99, 99);
  text-overflow: ellipsis;
  font-size: 32px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  text-align: left;
`;

const Frame312 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: column;
  align-items: center;
  flex: none;
  gap: 14px;
  box-sizing: border-box;
`;

const Button_0003 = styled.div`
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
  flex: none;
  gap: 10px;
  border: solid 1px rgb(28, 28, 28);
  border-radius: 4px;
  width: 337px;
  background-color: black;
  box-sizing: border-box;
  padding: 12px 89px;
`;

const LimitedToPublicProjectsThatAreOnGithub = styled.span`
  color: rgb(154, 154, 154);
  text-overflow: ellipsis;
  font-size: 16px;
  font-family: "Helvetica Neue", sans-serif;
  font-weight: 400;
  line-height: 135%;
  text-align: left;
`;

const Line35 = styled.div`
  width: 1039px;
  height: 0px;
  border-top: solid 1px rgba(0, 0, 0, 0.1);
  position: absolute;
  left: 201px;
  top: 1018px;
`;
